Merged (some of) revisions 4439, 5130, 5174 via zmerge from zmanda tree. 	* changer-src/chg-manual.sh.in: Fix quoting; fix gettext usage. 	* configure.in: 		New gettext routines. 	* server-src/amcheckdb.sh.in server-src/amcleanup.sh.in 	  server-src/amverifyrun.sh.in server-src/amrmtape.sh.in 	  server-src/amverify.sh.in server-src/amdump.sh.in 	  server-src/amfreetapes.sh.in amplot/amplot.sh.in 	  changer-src/chg-mtx.sh.in changer-src/chg-null.sh.in 	  changer-src/chg-manual.sh.in changer-src/chg-zd-mtx.sh.in 	  changer-src/chg-disk.sh.in changer-src/chg-juke.sh.in 	  changer-src/chg-rait.sh.in changer-src/chg-scsi.c 	  changer-src/chg-chs.sh.in changer-src/chg-multi.sh.in 	  changer-src/chg-mcutil.sh.in client-src/patch-system.sh.in 	  common-src/amcrypt.sh.in common-src/amaespipe.sh.in 	  common-src/amcrypt-ossl-asym.sh.in common-src/amcrypt-ossl.sh.in: 		Internationalize shell messages 	* autogen config/gettext-macros/nls.m4 	  config/gettext-macros/lib-link.m4: 		Update for autoconf version 2.6 autogen 	* oldrecover-src/amrecover.c recover-src/amrecover.c 	  server-src/amflush.c server-src/logfile.c server-src/amtrmlog.c 	  server-src/amlogroll.c server-src/amindexd.c server-src/amcheck.c 	  server-src/driver.c server-src/dumper.c server-src/chunker.c 	  server-src/planner.c server-src/reporter.c server-src/amadmin.c 	  server-src/amtape.c server-src/taper.c server-src/server_util.c 	  client-src/versionsuffix.c client-src/runtar.c 	  server-src/amtrmidx.c server-src/amcleanupdisk.c 	  server-src/getconf.c server-src/diskfile.c 	  changer-src/chg-scsi-chio.c client-src/noop.c server-src/infofile.c 	  server-src/amlabel.c client-src/sendbackup.c client-src/getfsent.c 	  client-src/killpgrp.c client-src/sendsize.c client-src/selfcheck.c 	  client-src/rundump.c client-src/calcsize.c restore-src/amidxtaped.c 	  restore-src/amrestore.c restore-src/amfetchdump.c Makefile.am 	  amandad-src/amandad.c common-src/genversion.c common-src/debug.c 	  common-src/error.c common-src/statfs.c common-src/amflock.c 	  common-src/file.c common-src/token.c common-src/security-util.c 	  common-src/conffile.c common-src/amanda.h common-src/amfeatures.c 	  tape-src/ammt.c tape-src/amdd.c tape-src/tapeio.c 	  tape-src/tapetype.c: 		Use amanda domain for LC_MESSAGES.
git-svn-id: https://amanda.svn.sourceforge.net/svnroot/amanda/amanda/trunk@357 a8d146d6-cc15-0410-8900-af154a0219e0

diff --git a/changer-src/chg-disk.sh.in b/changer-src/chg-disk.sh.in
--- a/changer-src/chg-disk.sh.in
+++ b/changer-src/chg-disk.sh.in
@@ -81,9 +81,24 @@ fi
 
 MYNAME=$0
 
+#+
+# Function to:
+#    Simplify gettext usage by allowing printf format
+#    strings for translators, use _() identifier for
+#    xgettext extraction similar to "C" usage and
+#    collapsing "printf `gettext fmt` ...", which is
+#    used everywhere, into one function.
+#-
+_() {
+	fmt=`gettext -d amanda "$1"`
+	shift
+	printf "$fmt" $*
+}
+
+
 TAPE=`amgetconf$SUF tapedev`
 if test X"$TAPE" == X""; then
-    echo "<none> tapedev not specified in amanda.conf."
+    echo `_ '<none> tapedev not specified in amanda.conf.'`
     exit 2
 fi
 SLOTDIR=`echo $TAPE | sed 's/^file://'`
@@ -99,11 +114,11 @@ isinteger() {
 
 # Need rwx access to the virtual tape itself.
 if ! test -d $SLOTDIR; then
-    echo "<none> Virtual-tape directory $SLOTDIR does not exist."
+    echo `_ '<none> Virtual-tape directory %s does not exist.' "$SLOTDIR"`
     exit 2
 fi
 if ! test -w $SLOTDIR; then
-    echo "<none> Virtual-tape directory $SLOTDIR is not writable."
+    echo `_ '<none> Virtual-tape directory %s is not writable.' "$SLOTDIR"`
     exit 2
 fi
 
@@ -120,21 +135,21 @@ fi
 
 CFDir=`dirname ${CHANGERFILE}`
 [ -d ${CFDir} -a -r ${CFDir} -a -w ${CFDir} -a -x ${CFDir} ] ||
-	{ echo "<none> $MYNAME: need 'rwx' access to '$CFDir'"; exit 2 ; }
+	{ echo `_ "<none> %s: need 'rwx' access to '%s'" "$MYNAME" "$CFDir"` ; exit 2 ; }
 
 # check or create changer metadata files
 ACCESSFILE=$CHANGERFILE-access
 [ -f $ACCESSFILE -a -r $ACCESSFILE -a -w $ACCESSFILE ] ||
 	echo 0 > $ACCESSFILE ||
-	{ echo "<none> $MYNAME: could not access or create '$ACCESSFILE'" ; exit 2 ; }
+	{ echo `_ "<none> %s: could not access or create '%s'" "$MYNAME" "$ACCESSFILE"` ; exit 2; }
 CLEANFILE=$CHANGERFILE-clean
 [ -f $CLEANFILE -a -r $CLEANFILE -a -w $CLEANFILE ] ||
 	echo 0 > $CLEANFILE ||
-	{ echo "<none> $MYNAME: could not access or create '$CLEANFILE'" ; exit 2 ; }
+	{ echo `_ "<none> %s: could not access or create '%s'" "$MYNAME" "$CLEANFILE"` ; exit 2 ; }
 SLOTFILE=$CHANGERFILE-slot
 [ -f $SLOTFILE -a -r $SLOTFILE -a -w $SLOTFILE ] ||
 	echo 0 > $SLOTFILE ||
-	{ echo "<none> $MYNAME: could not access or create '$SLOTFILE'" ; exit 2 ; }
+	{ echo `_ "<none> %s: could not access or create '%s'" "$MYNAME" "$SLOTFILE"` ; exit 2; }
 
 # read and check metadata
 ACCESSCOUNT=`cat $ACCESSFILE`
@@ -199,13 +214,13 @@ loadslot() {
     if [ $WHICHSLOT -ge $FIRSTSLOT -a $WHICHSLOT -le $LASTSLOT ]; then
       NEWSLOT=$WHICHSLOT
     else
-      echo "$WHICHSLOT illegal slot"
+      echo `_ '%s illegal slot' "$WHICHSLOT"`
       exit 1
     fi
   elif [ $WHICHSLOT = "clean" ]; then
     NEWSLOT=$CLEANSLOT
   else
-    echo "$WHICHSLOT illegal request"
+    echo `_ '%s illegal request' "$WHICHSLOT"`
     exit 1
   fi
   if [ $NEWSLOT = $CURSLOT ]; then
@@ -253,7 +268,7 @@ reset() {
 eject() {
   readstatus
   if [ $CURSLOT -le 0 ]; then
-    echo "0 Drive was not loaded"
+    echo `_ '0 Drive was not loaded'`
     exit 1
   else
     unload
@@ -310,7 +325,7 @@ while [ $# -ge 1 ];do
             eject
             ;;
     *)
-       echo "<none> Unknown option $1"
+       echo `_ '<none> Unknown option %s' "$1"`
        exit 2
        ;;
   esac
diff --git a/changer-src/chg-juke.sh.in b/changer-src/chg-juke.sh.in
--- a/changer-src/chg-juke.sh.in
+++ b/changer-src/chg-juke.sh.in
@@ -19,6 +19,21 @@
 # and changerdev, and deal with the possibility that there are several 
 # jukeboxes and several drives in each jukebox involved.
 
+#+
+# Function to:
+#    Simplify gettext usage by allowing printf format
+#    strings for translators, use _() identifier for
+#    xgettext extraction similar to "C" usage and
+#    collapsing "printf `gettext fmt` ...", which is
+#    used everywhere, into one function.
+#-
+_() {
+	fmt=`gettext -d amanda "$1"`
+	shift
+	printf "$fmt" $*
+}
+
+
 #
 # debugging...
 #
@@ -28,7 +43,7 @@ else
 	DBGFILE=/dev/null
 fi
 exec 2>$DBGFILE
-echo "args: $0 $*" >&2
+echo `_ 'args:'` $0 $* >&2
 set -x 
 
 #
@@ -107,7 +122,7 @@ unload_drive_n_clean() {
 	    then
 		:
 	    else
-		echo "$slot $tapedev unable to empty preceding tape from drive $drive"
+		echo `_ '%s %s unable to empty preceding tape from drive %s' "$slot" "$tapedev" "$drive"`
 		exit 1
 	    fi
 
@@ -136,7 +151,7 @@ load_drives() {
 	    juke load -j $changerdev drive $drive slot $rslot >&2
 	    if juke list -j $changerdev drive $drive | grep '(empty)' >&2
 	    then
-		echo "$slot $tapedev unable to load tape into drive"
+		echo `_ '$slot $tapedev unable to load tape into drive' "$slot" "$tapedev"`
 		exit 1
 	    fi
 	    count=`expr $count + 1`
@@ -152,7 +167,7 @@ load_drives() {
 	count=`expr $count + 1`
 	if [ $count -gt 24 ] 
 	then
-	    echo "$slot $tapedev never came online"
+	    echo `_ '%s %s never came online' "$slot" "$tapedev"`
 	    exit 1
 	fi
 	sleep 5
diff --git a/changer-src/chg-mcutil.sh.in b/changer-src/chg-mcutil.sh.in
--- a/changer-src/chg-mcutil.sh.in
+++ b/changer-src/chg-mcutil.sh.in
@@ -44,6 +44,19 @@ else
         SUF=
 fi
 
+#+
+# Function to:
+#    Simplify gettext usage by allowing printf format
+#    strings for translators, use _() identifier for
+#    xgettext extraction similar to "C" usage and
+#    collapsing "printf `gettext fmt` ...", which is
+#    used everywhere, into one function.
+#-
+_() {
+	fmt=`gettext -d amanda "$1"`
+	shift
+	printf "$fmt" $*
+}
 
 #
 # Load configuration data from the config file
@@ -55,7 +68,8 @@ myname=$0
 
 if [ ! -f "$ourconf" ]; then
         code=2
-        echo "Command Line -> $myname $@\nExit($code): $ourconf not found as listed in amanda.conf"
+        echo `_ 'Command Line ->'` $myname $@
+	echo `_ 'Exit(%s): %s not found as listed in amanda.conf' "$code" "$ourconf"` 1>&2
         exit $code
 fi
 
@@ -65,7 +79,8 @@ tmpval1=`grep ^mcutil $ourconf | awk -F\  '{print $2}'`
 tmpval2=`grep ^mcutil $ourconf | awk -F= '{print $2}'`
 if [ -z "$tmpval1" ] && [ -z "$tmpval2" ]; then
 	code=2
-	echo "Command Line -> $myname $@ \nExit($code): mcutil not specified in $ourconf"
+        echo `_ 'Command Line ->'` $myname $@
+	echo `_ 'Exit(%s): mcutil not specified in %s' "$code" "$ourconf"` 1>&2
 	exit $code
 elif [ -z "$tmpval1" ]; then
 	MCUTIL=$tmpval2
@@ -79,7 +94,8 @@ tmpval1=`grep ^tape $ourconf | awk -F\  '{print $2}'`
 tmpval2=`grep ^tape $ourconf | awk -F= '{print $2}'`
 if [ -z "$tmpval1" ] && [ -z "$tmpval2" ]; then
 	code=2
-	echo "Command Line -> $myname $@ \nExit($code): tape not specified in $ourconf"
+        echo `_ 'Command Line ->'` $myname $@
+	echo `_ 'Exit(%s): tape not specified in %s' "$code" "$ourconf"` 1>&2
 	exit $code
 elif [ -z "$tmpval1" ]; then
 	tape=$tmpval2
@@ -93,7 +109,8 @@ tmpval1=`grep ^firstslot $ourconf | awk -F\  '{print $2}'`
 tmpval2=`grep ^firstslot $ourconf | awk -F= '{print $2}'`
 if [ -z "$tmpval1" ] && [ -z "$tmpval2" ]; then
         code=2
-        echo "Command Line -> $myname $@ \nExit($code): firstslot not specified in $ourconf"
+        echo `_ 'Command Line ->'` $myname $@
+        echo `_ 'Exit(%s): firstslot not specified in %s' "$code" "$ourconf"` 1>&2
         exit $code
 elif [ -z "$tmpval1" ]; then
         firstslot=$tmpval2
@@ -107,8 +124,8 @@ tmpval1=`grep ^lastslot $ourconf | awk -F\  '{print $2}'`
 tmpval2=`grep ^lastslot $ourconf | awk -F= '{print $2}'`
 if [ -z "$tmpval1" ] && [ -z "$tmpval2" ]; then
         code=2
-        echo "Command Line -> $myname $@ \nExit($code): lastslot not specified in $ourconf"
-        exit $code
+        echo `_ 'Command Line ->'` $myname $@
+        echo `_ 'Exit(%s): lastslot not specified in %s' "$code" "$ourconf"` 1>&2
 elif [ -z "$tmpval1" ]; then
         lastslot=$tmpval2
 else
@@ -121,7 +138,8 @@ tmpval1=`grep ^use_cleaning $ourconf | awk -F\  '{print $2}'`
 tmpval2=`grep ^use_cleaning $ourconf | awk -F= '{print $2}'`
 if [ -z "$tmpval1" ] && [ -z "$tmpval2" ]; then
         code=2
-        echo "Command Line -> $myname $@ \nExit($code): use_cleaning not specified in $ourconf"
+        echo `_ 'Command Line ->'` $myname $@
+        echo `_ 'Exit(%s): use_cleaning not specified in %s' "$code" "$ourconf"` 1>&2
         exit $code
 elif [ -z "$tmpval1" ]; then
         use_cleaning=$tmpval2
@@ -135,7 +153,8 @@ tmpval1=`grep ^cleanslot $ourconf | awk -F\  '{print $2}'`
 tmpval2=`grep ^cleanslot $ourconf | awk -F= '{print $2}'`
 if [ -z "$tmpval1" ] && [ -z "$tmpval2" ]; then
         code=2
-        echo "Command Line -> $myname $@ \nExit($code): cleanslot not specified in $ourconf"
+        echo `_ 'Command Line ->'` $myname $@
+        echo `_ 'Exit(%s): cleanslot not specified in %s' "$code" "$ourconf"` 1>&2
         exit $code
 elif [ -z "$tmpval1" ]; then
         cleanslot=$tmpval2
@@ -149,7 +168,8 @@ tmpval1=`grep ^cleansleep $ourconf | awk -F\  '{print $2}'`
 tmpval2=`grep ^cleansleep $ourconf | awk -F= '{print $2}'`
 if [ -z "$tmpval1" ] && [ -z "$tmpval2" ]; then
 	code=2
-	echo "Command Line -> $myname $@ \nExit($code): cleansleep not specified in $ourconf"
+        echo `_ 'Command Line ->'` $myname $@
+        echo `_ 'Exit(%s): cleansleep not specified in %s' "$code" "$ourconf"` 1>&2
 	exit $code
 elif [ -z "$tmpval1" ]; then
 	cleansleep=$tmpval2
@@ -163,7 +183,8 @@ tmpval1=`grep ^cleanme $ourconf | awk -F\  '{print $2}'`
 tmpval2=`grep ^cleanme $ourconf | awk -F= '{print $2}'`
 if [ -z "$tmpval1" ] && [ -z "$tmpval2" ]; then
 	code=2
-	echo "Command Line -> $myname $@ \nExit($code): cleanme not specified in $ourconf"
+        echo `_ 'Command Line ->'` $myname $@
+        echo `_ 'Exit(%s): cleanme not specified in %s' "$code" "$ourconf"` 1>&2
 	exit $code
 elif [ -z "$tmpval1" ]; then
 	cleanme=$tmpval2
@@ -177,7 +198,8 @@ tmpval1=`grep ^cleanfile $ourconf | awk -F\  '{print $2}'`
 tmpval2=`grep ^cleanfile $ourconf | awk -F= '{print $2}'`
 if [ -z "$tmpval1" ] && [ -z "$tmpval2" ]; then
         code=2
-        echo "Command Line -> $myname $@ \nExit($code): cleanfile not specified in $ourconf"
+        echo `_ 'Command Line ->'` $myname $@
+        echo `_ 'Exit(%s): cleanfile not specified in %s' "$code" "$ourconf"` 1>&2
         exit $code
 elif [ -z "$tmpval1" ]; then
         cleanfile=$tmpval2
@@ -191,7 +213,8 @@ tmpval1=`grep ^lastfile $ourconf | awk -F\  '{print $2}'`
 tmpval2=`grep ^lastfile $ourconf | awk -F= '{print $2}'`
 if [ -z "$tmpval1" ] && [ -z "$tmpval2" ]; then
 	code=2
-	echo "Command Line -> $myname $@ \nExit($code): lastfile not specified in $ourconf"
+        echo `_ 'Command Line ->'` $myname $@
+        echo `_ 'Exit(%s): lastfile not specified in %s' "$code" "$ourconf"` 1>&2
 	exit $code
 elif [ -z "$tmpval1" ]; then
 	lastfile=$tmpval2
@@ -205,7 +228,8 @@ tmpval1=`grep ^currentslot $ourconf | awk -F\  '{print $2}'`
 tmpval2=`grep ^currentslot $ourconf | awk -F= '{print $2}'`
 if [ -z "$tmpval1" ] && [ -z "$tmpval2" ]; then
 	code=2
-	echo "Command Line -> $myname $@ \nExit($code): currentslot not specified in $ourconf"
+        echo `_ 'Command Line ->'` $myname $@
+        echo `_ 'Exit(%s): currentslot not specified in %s' "$code" "$ourconf"` 1>&2
 	exit $code
 elif [ -z "$tmpval1" ]; then
 	currentslot=$tmpval2
@@ -219,7 +243,8 @@ tmpval1=`grep ^logfile $ourconf | awk -F\  '{print $2}'`
 tmpval2=`grep ^logfile $ourconf | awk -F= '{print $2}'`
 if [ -z "$tmpval1" ] && [ -z "$tmpval2" ]; then
 	code=2
-	echo "Command Line -> $myname $@ \nExit($code): logfile not specified in $ourconf"
+        echo `_ 'Command Line ->'` $myname $@
+        echo `_ 'Exit(%s): logfile not specified in %s' "$code" "$ourconf"` 1>&2
 	exit $code
 elif [ -z "$tmpval1" ]; then
 	logfile=$tmpval2
@@ -235,7 +260,8 @@ tmpval1=`grep ^slot0source $ourconf | awk -F\  '{print $2}'`
 tmpval2=`grep ^slot0source $ourconf | awk -F= '{print $2}'`
 if [ -z "$tmpval1" ] && [ -z "$tmpval2" ]; then
 	code=2
-	echo "Command Line -> $myname $@ \nExit($code): slot0source not specified in $ourconf"
+        echo `_ 'Command Line ->'` $myname $@
+        echo `_ 'Exit(%s): slot0source not specified in %s' "$code" "$ourconf"` 1>&2
 	exit $code
 elif [ -z "$tmpval1" ]; then
 	slot0source=$tmpval2
@@ -258,7 +284,7 @@ current=`cat $currentslot`
 
 # Start logging to $logfile
 echo "\n\n==== `date` ====" >> $logfile
-echo "Command Line -> $myname $@" >> $logfile
+echo `_ 'Command Line ->'` $myname $@ >> $logfile
 
 
 #
@@ -293,10 +319,10 @@ if [ $use_cleaning -eq 1 ]; then
   fi
 
   if [ $diffday -gt $cleanme ] || [ $diffyear -ge 1 ];then
-     if [ $diffyear -ge 1 ];then
-	  echo "Warning, it's been $diffyear year(s) & $diffday days since you last cleaned the tape drive!"
+     if [ $diffyea" -ge 1 ];then
+	  echo `_ "Warning, it's been %s year(s) & %s day(s) since you last cleaned the tape drive!" "$diffyear" "$diffday"`
      else
-	  echo "Warning, it's been $diffday days since you last cleaned the tape drive!"
+	  echo `_ "Warning, it's been %s day(s) since you last cleaned the tape drive!" "$diffday"`
      fi
   fi
 
@@ -308,9 +334,9 @@ fi
 # If so, determine what slot is the tape from
 #
 readstatus() {
-  echo -n "querying tape drive....." >> $logfile
+  echo `_ "querying tape drive....."` >> $logfile
   used=`expr \`$MCUTIL -e drive | tr = \] | cut -d\] -f2\` - $slot0source`
-  echo " Done" >> $logfile
+  echo `_ " Done"` >> $logfile
 
   # Give changer a chance to reset itself
   sleep 3
@@ -321,7 +347,7 @@ readstatus() {
 # If tape is in the drive, eject it
 #
 eject() {
-  echo "tape drive eject was called" >> $logfile
+  echo `_ "tape drive eject was called"` >> $logfile
 
   readstatus 
 
@@ -333,18 +359,18 @@ eject() {
   fi
 
   if [ $code -eq 0 ];then
-    answer="Cartridge $used successfully ejected from $tape"
-    echo "Exit($code): $answer" >> $logfile
-    echo $current $tape		#For amtape output  
+    answer=`_ 'Cartridge %s successfully ejected from %s' "$used" "$tape"`
+    echo `_ "Exit(%s): %s" "$code" "$answer"` >> $logfile
+    echo $current $answer	#For amtape output  
     return $code
   elif [ $code -eq 1 ];then
-    answer="No Cartridge in Tape Drive"
-    echo "Exit($code): $answer" >> $logfile
+    answer=`_ "No Cartridge in Tape Drive"`
+    echo `_ 'Exit(%s): %s' "$code" "$answer"` >> $logfile
     echo $current $answer	#For amtape output
     exit $code
   else
-    answer="Tape abnormally failed"
-    echo "Exit($code): $answer" >> $logfile
+    answer=`_ 'Tape abnormally failed'`
+    echo `_ 'Exit(%s): %s' "$code" "$answer"` >> $logfile
     echo $current $answer	#For amtape output
     exit $code
   fi
@@ -357,7 +383,7 @@ eject() {
 # and inserting the tape in $firstslot
 #
 reset() {
-  echo "tape drive reset was called" >> $logfile
+  echo `_ 'tape drive reset was called'` >> $logfile
 
   readstatus
 
@@ -371,15 +397,15 @@ reset() {
 
   if [ $code -eq 0 ];then
     echo $firstslot > $currentslot
-    answer="$firstslot - Tape drive was successfully reset"
+    answer=`_ '%s - Tape drive was successfully reset' "$firstslot"`
   elif [ $code -eq 1 ];then
-    answer="$firstslot - Tape drive reset failed\nCommand -> $res"
+    answer=`_ '%s - Tape drive reset failed\nCommand -> %s' "$firstslot" "$res"`
   else
     code=2
-    answer="$firstlot - Tape abnormally failed -> $res"
+    answer=`_ '%s - Tape abnormally failed -> %s' "$firstslot" "$res"`
   fi
 
-  echo "Exit($code): slot $answer" >> $logfile
+  echo `_ 'Exit(%s): slot %s' "$code" "$answer"` >> $logfile
   echo $firstslot	#For amtape output 
   exit $code
 }
@@ -391,7 +417,7 @@ reset() {
 # Load a specific cartridge into the changer
 #
 loadslot() {
-  echo "loadslot was called" >> $logfile
+  echo `_ "loadslot was called"` >> $logfile
 
   readstatus
 
@@ -416,8 +442,8 @@ loadslot() {
 	  if [ $whichslot = advance ];then
 	     echo $load > $currentslot
 	     code=0
-	     answer="advancing to slot $load"
-	     echo "Exit($code): $answer" >> $logfile
+	     answer=`_ 'advancing to slot %s' "$load"`
+	     echo `_ 'Exit(%s): %s' "$code" "$answer"` >> $logfile
 	     echo $load $code
 	     exit $code
 	  else
@@ -454,16 +480,16 @@ loadslot() {
 	     reset
 	  else
 	     code=1
-	     answer="Cleaning not enabled in config" >> $logfile
-	     echo "Exit($code): $answer" >> $logfile
+	     answer=`_ "Cleaning not enabled in config"`
+	     echo `_ 'Exit(%s): %s' "$code" "$answer"` >> $logfile
 	     echo $cleanslot $answer
 	     exit $code
 	  fi
 	  ;;
     *)
        code=1
-       answer="\"$whichslot\" invalid menu option"
-       echo "Exit($code): slot $answer" >> $logfile
+       answer=`_ '"%s" invalid menu option' "$whichslot"`
+       echo `_ 'Exit(%s): %s' "$code" "$answer"` >> $logfile
        echo "$answer"
        exit $code
        ;;
@@ -480,8 +506,8 @@ movetape() {
     # If the requested slot is already loaded in the tape drive
     if [ $load -eq $used ]; then
         code=0
-	answer="$load is already loaded"
-        echo "Exit($code): slot $answer" >> $logfile
+	answer=`_ 'slot %s is already loaded' "$load"`
+        echo `_ 'Exit(%s): %s' "$code" "$answer"` >> $logfile
         echo $load $tape	# For amtape output
         exit $code
     elif [ $used -ge $firstslot ];then
@@ -491,23 +517,23 @@ movetape() {
 	echo $load $tape 	# For amtape output
     fi
 
-    echo "Loading slot $load into Tape drive" >> $logfile
+    echo `_ 'Loading slot %s into Tape drive' "$load"` >> $logfile
     $MCUTIL -m  slot:$load drive
     code=$?
 
     if [ $code -eq 0 ];then
 	echo $load > $currentslot
-	answer="Cartridge $load successfully loaded in Tape drive"
+	answer=`_ 'Cartridge %s successfully loaded in Tape drive' "$load"`
     else
-	answer="Cartridge $load failed to load in Tape drive"
+	answer=`_ 'Cartridge %s failed to load in Tape drive' "$load"`
     fi
-	echo "Exit($code): $answer" >> $logfile
-	exit $code
+    echo `_ 'Exit(%s): %s' "$code" "$answer"` >> $logfile
+    exit $code
 }
 
 
 info() {
-  echo "tape drive info was called" >> $logfile
+  echo `_ 'tape drive info was called'` >> $logfile
 
   readstatus
 
@@ -517,7 +543,7 @@ info() {
 
   code=0
   answer="$used $lastslot 1"
-  echo "Exit($code): $answer" >> $logfile
+  echo `_ 'Exit(%s): %s' "$code" "$answer"` >> $logfile
   echo "$answer"
   exit $code
 }
@@ -544,21 +570,21 @@ info() {
 	    eject
 	    ;;
     --help|-help)
-	    echo "-slot {current|next|previous|first|last|$firstslot-$lastslot|clean}"
-	    echo "	current  - show contents of current slot"
-	    echo "	next     - load tape from next slot"
-	    echo "	previous - load tape from previous slot"
-	    echo "	first	 - load tape from first slot"
-	    echo "	last	 - load tape from last slot"
-	    echo "	$firstslot - $lastslot	 - load tape from slot <slot #>"
-	    echo "	clean	 - Clean the drive"
-	    echo "-device   : Show current tape device"
-	    echo "-reset    : Reset changer to known state"
-	    echo "-eject    : Eject current tape from drive"
-	    echo "-info     : Output {current slot | # of slots | can changer go backwards}"
-	    echo "-help     : Display this help"
+	    echo `_ '-slot {current|next|previous|first|last|%s-%s|clean}' "$firstslot" "$lastslot"`
+	    echo `_ '	current  - show contents of current slot'`
+	    echo `_ '	next     - load tape from next slot'`
+	    echo `_ '	previous - load tape from previous slot'`
+	    echo `_ '	first	 - load tape from first slot'`
+	    echo `_ '	last	 - load tape from last slot'`
+	    echo `_ '	%s - %s	 - load tape from slot <slot #>' "$firstslot" "$lastslot"`
+	    echo `_ '	clean	 - Clean the drive'`
+	    echo `_ '-device   : Show current tape device'`
+	    echo `_ '-reset    : Reset changer to known state'`
+	    echo `_ '-eject    : Eject current tape from drive'`
+	    echo `_ '-info     : Output {current slot | # of slots | can changer go backwards}'`
+	    echo `_ '-help     : Display this help'`
 	    ;;
     *)
-       echo "<usage> $myname -{slot|device|reset|eject|help}"
+       echo `_ '<usage> %s -{slot|device|reset|eject|help}" "$myname"`
        ;;
  esac
diff --git a/client-src/patch-system.sh.in b/client-src/patch-system.sh.in
--- a/client-src/patch-system.sh.in
+++ b/client-src/patch-system.sh.in
@@ -8,6 +8,21 @@ prefix="@prefix@"
 exec_prefix="@exec_prefix@"
 libexecdir="@libexecdir@"
 
+#+
+# Function to:
+#    Simplify gettext usage by allowing printf format
+#    strings for translators, use _() identifier for
+#    xgettext extraction similar to "C" usage and
+#    collapsing "printf `gettext fmt` ...", which is
+#    used everywhere, into one function.
+#-
+function _() {
+	fmt=`gettext -d amanda "$1"`
+	shift
+	printf "$fmt" $*
+}
+
+
 USE_VERSION_SUFFIXES="@USE_VERSION_SUFFIXES@"
 if test "$USE_VERSION_SUFFIXES" = "yes"; then
 	SUF="-@VERSION@"
@@ -78,24 +93,24 @@ while [ $# != 0 ]; do
     --tape-port=?*)
 	TAPE_PORT=`echo $1 | sed -e 's/[^=]*=//'`;;
     --usage | --help | -h)
-	echo "call this script with zero or more of the following arguments:"
-	echo "--version-suffix=<suffix>: append to program names [$SUF]"
-	echo "--service-suffix=<suffix>: append to service names [$SERVICE_SUFFIX]"
-	echo "--libexecdir=<dirname>: where daemons should be looked for [$libexecdir]"
-	echo "--inetd=<pathname>: full pathname of inetd.conf [$INETDCONF]"
-	echo "--services=<pathname>: full pathname of services [$SERVICES]"
-	echo "    an empty pathname or /dev/null causes that file to be skipped"
-	echo "--user=<username>: run deamons as this user [$USER]"
-	echo "--enable/disable-client: enable/disable amandad [`$ENABLE_AMANDAD && echo enabled || echo disabled`]"
-	echo "--enable/disable-index: enable/disable index server [`$ENABLE_INDEX && echo enabled || echo disabled`]"
-	echo "--enable/disable-tape: enable/disable tape server [`$ENABLE_TAPE && echo enabled || echo disabled`]"
-	echo "--client-port=<num>: amandad port number [$CLIENT_PORT]"
-	echo "--kclient-port=<num>: kamandad port number [$KCLIENT_PORT]"
-	echo "--index-port=<num>: index server port number [$INDEX_PORT]"
-	echo "--tape-port=<num>: tape server port number [$TAPE_PORT]"
+	echo `_ 'call this script with zero or more of the following arguments:'`
+	echo `_ '--version-suffix=<suffix>: append to program names [%s]' "$SUF"`
+	echo `_ '--service-suffix=<suffix>: append to service names [%s]' "$SERVICE_SUFFIX"`
+	echo `_ '--libexecdir=<dirname>: where daemons should be looked for [%s]' "$libexecdir"`
+	echo `_ '--inetd=<pathname>: full pathname of inetd.conf [%s]' "$INETDCONF"`
+	echo `_ '--services=<pathname>: full pathname of services [%s]' "$SERVICES"`
+	echo `_ '\tan empty pathname or /dev/null causes that file to be skipped'`
+	echo `_ '--user=<username>: run deamons as this user [%s]' "$USER"`
+	echo `_ '--enable/disable-client: enable/disable amandad [%s]' \`$ENABLE_AMANDAD && echo enabled || echo disabled\``
+	echo `_ '--enable/disable-index: enable/disable index server [%s]' \`$ENABLE_INDEX && echo enabled || echo disabled\``
+	echo `_ '--enable/disable-tape: enable/disable tape server [%s]' \`$ENABLE_TAPE && echo enabled || echo disabled\``
+	echo `_ '--client-port=<num>: amandad port number [%s]' "$CLIENT_PORT"`
+	echo `_ '--kclient-port=<num>: kamandad port number [%s]' "$KCLIENT_PORT"`
+	echo `_ '--index-port=<num>: index server port number [%s]' "$INDEX_PORT"`
+	echo `_ '--tape-port=<num>: tape server port number [%s]' "$TAPE_PORT"`
 	exec true;;
     *)
-	echo "$0: invalid argument $1.  run with -h for usage" >&2
+	echo `_ '%s: invalid argument %s.  run with -h for usage\n' "$0" "$1"` >&2
 	exec false;;
     esac
     shift
@@ -113,19 +128,22 @@ elif [ -f "$SERVICES" ]; then
 	    echo "amidxtape${SERVICE_SUFFIX} ${TAPE_PORT}/tcp"
 	} > "$TEMP"
 	if diff "$SERVICES" "$TEMP" >/dev/null 2>/dev/null; then
-		echo "$SERVICES is up to date"
+		echo `_ '%s is up to date' "$SERVICES"`
 	else
-		cp "$TEMP" "$SERVICES" || echo "cannot patch $SERVICES"
+		cp "$TEMP" "$SERVICES" || echo `_ 'cannot patch %s' "$SERVICES"`
 	fi
 	rm -f "$TEMP"
 else
-	echo "$SERVICES not found!"
+	echo `_ '%s not found!' "$SERVICES"`
 fi
 if [ "$INETDCONF" = /dev/null ]; then :
 elif [ -f "$INETDCONF" ]; then
-	$ENABLE_AMANDAD && test ! -f $libexecdir/amandad$SUF && echo "warning: $libexecdir/amandad$SUF does not exist" >&2
-	$ENABLE_INDEX && test ! -f $libexecdir/amindexd$SUF && echo "warning: $libexecdir/amindexd$SUF does not exist" >&2
-	$ENABLE_TAPE && test ! -f $libexecdir/amidxtaped$SUF && echo "warning: $libexecdir/amidxtaped$SUF does not exist" >&2
+	err=`_ 'warning: %s/amandad%s does not exist' "$libexecdir" "$SUF"`
+	$ENABLE_AMANDAD && test ! -f $libexecdir/amandad$SUF && echo "$err" >&2
+	err=`_ 'warning: %s/amindexd%s does not exist' "$libexecdir" "$SUF"`
+	$ENABLE_INDEX && test ! -f $libexecdir/amindexd$SUF && echo "$err" >&2
+	err=`_ 'warning: %s/amidxtaped%s does not exist' "$libexecdir" "$SUF"`
+	$ENABLE_TAPE && test ! -f $libexecdir/amidxtaped$SUF && echo "$err" >&2
 	TEMP="$INETDCONF.new"
 	{
 	    egrep < "$INETDCONF" -v "^(amanda|amandaidx|amidxtape)${SERVICE_SUFFIX}[ 	]"
@@ -134,11 +152,14 @@ elif [ -f "$INETDCONF" ]; then
 	    $ENABLE_TAPE && echo "amidxtape${SERVICE_SUFFIX} stream tcp nowait $USER $libexecdir/amidxtaped$SUF amidxtaped$SUF"
 	} > "$TEMP"
 	if diff "$INETDCONF" "$TEMP" >/dev/null 2>/dev/null; then
-		echo "$INETDCONF is up to date"
+		fmt="%s is up to date\n"
+		printf $fmt $INETDCONF
 	else
-		cp "$TEMP" "$INETDCONF" || echo "cannot patch $INETDCONF"
+		fmt="cannot patch %s\n"
+		cp "$TEMP" "$INETDCONF" || printf $fmt $INETDCONF
 	fi
 	rm -f "$TEMP"
 else
-	echo "$INETDCONF not found!"
+	fmt="%s not found!\n"
+	printf $fmt $INETDCONF
 fi
diff --git a/common-src/amcrypt-ossl-asym.sh.in b/common-src/amcrypt-ossl-asym.sh.in
--- a/common-src/amcrypt-ossl-asym.sh.in
+++ b/common-src/amcrypt-ossl-asym.sh.in
@@ -50,12 +50,27 @@ MAGIC='AmAnDa+OpEnSsL'
 ME=`basename "$0"`
 WORKDIR="/tmp/.${ME}.$$"
 
+#+
+# Function to:
+#    Simplify gettext usage by allowing printf format
+#    strings for translators, use _() identifier for
+#    xgettext extraction similar to "C" usage and
+#    collapsing "printf `gettext fmt` ...", which is
+#    used everywhere, into one function.
+#-
+_() {
+	fmt=`gettext -d amanda "$1"`
+	shift
+	printf "$fmt" $*
+}
+
+
 # first things first
 if [ -z "${OPENSSL:=`which openssl`}" ]; then
-	echo "${ME}: openssl not found" >&2
+	echo `_ '%s: %s not found' "${ME}" "openssl"` >&2
 	exit 1
 elif [ ! -x "${OPENSSL}" ]; then
-	echo "${ME}: can't execute openssl (${OPENSSL})" >&2
+	echo `_ "%s: can't execute openssl (%s)" "${ME}" "${OPENSSL}"` >&2
 	exit 1
 fi
 
@@ -65,8 +80,8 @@ if [ -n "${PASSPHRASE}" ]; then
 	OSSL_VERSION=`eval \"${OPENSSL}\" version |cut -d\  -f2`
 	case "${OSSL_VERSION}" in
 	 ''|0.[0-8].*|0.9.[0-6]*|0.9.7|0.9.7[a-c]*)
-		echo "${ME}: ${OPENSSL} is version ${OSSL_VERSION}" >&2
-		echo "${ME}: Using pass phrase kluge for OpenSSL version >=0.9.7d" >&2
+		echo `_ '%s: %s is version %s' "${ME}" "${OPENSSL}" "${OSSL_VERSION}"` >&2
+		echo `_ '%s: Using pass phrase kluge for OpenSSL version >=0.9.7d' "${ME}"` >&2
 		PASS_FROM_STDIN=yes
 		;;
 	esac
@@ -74,7 +89,7 @@ fi
 
 mkdir -m 700 "${WORKDIR}"
 if [ $? -ne 0 ]; then
-	echo "${ME}: failed to create temp directory" >&2
+	echo `_ '%s: failed to create temp directory' "${ME}"` >&2
 	exit 1
 fi
 # ignore SIGINT
@@ -97,7 +112,7 @@ encrypt() {
 	[ $? -eq 0 ] || return 1
 
 	# print magic
-	printf %s "${MAGIC}"
+	printf "%s" "${MAGIC}"
 
 	# print the encrypted cipher key, preceded by size
 	ls -l "${WORKDIR}/pass.ciphertext" | awk '{ printf("%-10d", $5) }'
@@ -110,10 +125,10 @@ encrypt() {
 
 decrypt() {
 	# read magic
-	magicsize=`printf %s "${MAGIC}" | wc -c | sed 's/^ *//'`
+	magicsize=`printf "%s" "${MAGIC}" | wc -c | sed 's/^ *//'`
 	magic=`dd bs=$magicsize count=1 2>/dev/null`
 	if [ "$magic" != "${MAGIC}" ]; then
-		echo "${ME}: bad magic" >&2
+		echo `_ '%s: bad magic' "${ME}"` >&2
 		return 1
 	fi
 
@@ -121,7 +136,7 @@ decrypt() {
 	n=`dd bs=10 count=1 2>/dev/null`
 	[ $n -gt 0 ] 2>/dev/null
 	if [ $? -ne 0 ]; then
-		echo "${ME}: bad header" >&2
+		echo `_ '%s: bad header' "${ME}"` >&2
 		return 1
 	fi
 
@@ -146,10 +161,10 @@ decrypt() {
 
 if [ "$1" = -d ]; then
 	if [ -z "${PRIVKEY}" ]; then
-		echo "${ME}: must specify private key for decryption" >&2
+		echo `_ '%s: must specify private key for decryption' "${ME}"` >&2
 		exit 1
 	elif [ ! -r "${PRIVKEY}" ]; then
-		echo "${ME}: can't read private key from ${PRIVKEY}" >&2
+		echo `_ "%s: can't read private key from %s" "${ME}" "${PRIVKEY}"` >&2
 		exit 1
 	fi
 
@@ -161,21 +176,21 @@ if [ "$1" = -d ]; then
 
 	decrypt
 	if [ $? -ne 0 ]; then
-		echo "${ME}: decryption failed" >&2
+		echo `_ '%s: decryption failed' "${ME}"` >&2
 		exit 1
 	fi
 else
 	if [ -z "${PUBKEY}" ]; then
-		echo "${ME}: must specify public key for encryption" >&2
+		echo `_ '%s: must specify public key for encryption' "${ME}"` >&2
 		exit 1
 	elif [ ! -r "${PUBKEY}" ]; then
-		echo "${ME}: can't read public key from ${PUBKEY}" >&2
+		echo `_ "%s: can't read public key from %s" "${ME}" "${PUBKEY}"` >&2
 		exit 1
 	fi
 
 	encrypt
 	if [ $? -ne 0 ]; then
-		echo "${ME}: encryption failed" >&2
+		echo `_ '%s: encryption failed' "${ME}"` >&2
 		exit 1
 	fi
 fi
diff --git a/common-src/amcrypt-ossl.sh.in b/common-src/amcrypt-ossl.sh.in
--- a/common-src/amcrypt-ossl.sh.in
+++ b/common-src/amcrypt-ossl.sh.in
@@ -17,11 +17,26 @@ PATH=/bin:/usr/bin:/usr/local/bin:/usr/ssl/bin:/usr/local/ssl/bin
 export PATH
 ME=`basename "$0"`
 
+#+
+# Function to:
+#    Simplify gettext usage by allowing printf format
+#    strings for translators, use _() identifier for
+#    xgettext extraction similar to "C" usage and
+#    collapsing "printf `gettext fmt` ...", which is
+#    used everywhere, into one function.
+#-
+_() {
+	fmt=`gettext -d amanda "$1"`
+	shift
+	printf "$fmt" $*
+}
+
+
 if [ -z "${OPENSSL:=`which openssl`}" ]; then
-	echo "${ME}: openssl not found" >&2
+	echo `_ '%s: %s not found' "${ME}" "openssl"` >&2
 	exit 1
 elif [ ! -x "${OPENSSL}" ]; then
-	echo "${ME}: can't execute openssl (${OPENSSL})" >&2
+	echo `_ '%s: can't execute openssl (%s)' "${ME}" "${OPENSSL}"` >&2
 	exit 1
 fi
 
diff --git a/common-src/amcrypt.sh.in b/common-src/amcrypt.sh.in
--- a/common-src/amcrypt.sh.in
+++ b/common-src/amcrypt.sh.in
@@ -18,18 +18,37 @@ export PATH
 
 AESPIPE=`which aespipe`
 
+#+
+# Function to:
+#    Simplify gettext usage by allowing printf format
+#    strings for translators, use _() identifier for
+#    xgettext extraction similar to "C" usage and
+#    collapsing "printf `gettext fmt` ...", which is
+#    used everywhere, into one function.
+#-
+_() {
+	fmt=`gettext -d amanda "$1"`
+	shift
+	printf "$fmt" $*
+}
+
+
 if [ $? -ne 0 ] ; then
-	echo "amcrypt: aespipe not found in $PATH" >&2
+	echo `_ '%s: %s not found in %s' "$0" "aespipe" "$PATH"` >&2
         exit 2
 fi
 
 if [ ! -x $AESPIPE ] ; then
-        echo "amcrypt: aespipe it's not executable" >&2
+	echo `_ '%s: %s is not executable' "$0" "aespipe"` >&2
         exit 2
 fi
 
 if [ ! -x $AM_AESPIPE ] ; then
-        echo "amcrypt: $AM_AESPIPE not found or it's not executable"  >&2
+        echo `_ '%s: %s was not found' "$0" "$AM_AESPIPE"` >&2
+        exit 2
+fi
+if [ ! -x $AM_AESPIPE ] ; then
+        echo `_ '%s: %s is not executable' "$0" "$AM_AESPIPE"` >&2
         exit 2
 fi
 
diff --git a/server-src/amcheckdb.sh.in b/server-src/amcheckdb.sh.in
--- a/server-src/amcheckdb.sh.in
+++ b/server-src/amcheckdb.sh.in
@@ -20,6 +20,20 @@ else
 	SUF=
 fi
 
+#+
+# Function to:
+#    Simplify gettext usage by allowing printf format
+#    strings for translators, use _() identifier for
+#    xgettext extraction similar to "C" usage and
+#    collapsing "printf `gettext fmt` ...", which is
+#    used everywhere, into one function.
+#-
+function _() {
+	fmt=`gettext -d amanda "$1"`
+	shift
+	printf "$fmt" $*
+}
+
 Program=`basename $0`
 
 log () {
@@ -63,8 +77,11 @@ fi
 
 Amadmin=$sbindir/amadmin$SUF
 
+[ ! -f $Amadmin ] \
+	&& echo `_ '%s was not found' $Amadmin` >&2 \
+	&& exit 1
 [ ! -x $Amadmin ] \
-	&& echo "$Amadmin not found or not executable" >&2 \
+	&& echo `_ '%s is not executable' $Amadmin` >&2 \
 	&& exit 1
 
 $Amadmin $Config export "$@"\
@@ -79,9 +96,9 @@ $Amadmin $Config export "$@"\
 		[ "$TAPE" = "" ] && continue
 		grep " $TAPE " $TapeList 2>/dev/null >/dev/null
 		[ $? != 0 ] \
-			&& echo "Tape $TAPE missing in $TapeList"
+			&& echo `_ 'Tape %s missing in %s' "$TAPE" "$TapeList"`
 	done
 
-echo "Ready."
+echo `_ 'Ready.'`
 
 exit 0
diff --git a/server-src/amcleanup.sh.in b/server-src/amcleanup.sh.in
--- a/server-src/amcleanup.sh.in
+++ b/server-src/amcleanup.sh.in
@@ -47,6 +47,20 @@ else
 	SUF=
 fi
 
+#+
+# Function to:
+#    Simplify gettext usage by allowing printf format
+#    strings for translators, use _() identifier for
+#    xgettext extraction similar to "C" usage and
+#    collapsing "printf `gettext fmt` ...", which is
+#    used everywhere, into one function.
+#-
+function _() {
+	fmt=`gettext -d amanda "$1"`
+	shift
+	printf "$fmt" $*
+}
+
 if test -h /proc/1/exe ; then
 	if test $# -ge 2 && test "$1" == "-k" ; then
 		KILL_ENABLE=1
@@ -58,12 +72,12 @@ if test -h /proc/1/exe ; then
 		conf=$1
 		shift;
 	else
-		echo "Usage: amcleanup [-k] conf"
+		echo `_ 'Usage: amcleanup [-k] conf'`
 		exit 1
 	fi
 else
 	if test $# -lt 1 ; then
-		echo "Usage: amcleanup conf"
+		echo `_ 'Usage: amcleanup conf'`
 		exit 1
 	else
 		conf=$1
@@ -73,7 +87,7 @@ else
 fi
 
 if test ! -d $confdir/$conf ; then
-	echo "amcleanup: could not cd into $confdir/$conf"
+	echo `_ '%s: could not cd into %s' "amcleanup" "$confdir/$conf"`
 	exit 1
 fi
 
@@ -82,7 +96,7 @@ cd $confdir/$conf
 logdir=`amgetconf$SUF $conf logdir "$@"`
 rc=$?
 if test $rc -ne 0 ; then
-	echo "amcleanup: 'amgetconf$SUF logdir' exited with status: $rc" 1>&2
+	echo `_ '%s: "%s" exited with status: %s' "amcleanup" "amgetconf$SUF logdir" "$rc"` 1>&2
 	exit 1
 fi
 logfile=$logdir/log
@@ -91,13 +105,13 @@ erramflush=$logdir/amflush
 tapecycle=`amgetconf$SUF $conf tapecycle "$@"`
 rc=$?
 if test $rc -ne 0 ; then
-	echo "amcleanup: 'amgetconf$SUF tapecycle' exited with status: $rc " 1>&2
+	echo `_ '%s: "%s" exited with status: %s' "amcleanup" "amgetconf$SUF tapecycle" "$rc"` 1>&2
 	exit 1
 fi
 dumpuser=`amgetconf$SUF $conf dumpuser "$@"`
 rc=$?
 if test $rc -ne 0 ; then
-	echo "amcleanup: 'amgetconf$SUF $conf dumpuser' exited with status: $rc" 1>&2
+	echo `_ '%s: "%s" exited with status: %s' "amcleanup" "amgetconf$SUF $conf dumpuser" "$rc"` 1>&2
 	exit 1
 fi
 
@@ -194,7 +208,7 @@ if test ${KILL_ENABLE} -eq 1 ; then
 						match_name=$?
 						pid_uid="`cat /proc/${search_pid}/status 2>/dev/null | grep Uid | awk '//{split($_,i); print i[2]}'`"
 						if test ${match_name} -eq 0  && test "${pid_uid}" == "${search_user}" ; then
-							echo "amcleanup: Process ${search_name} found running at pid #${search_pid}."
+							echo `_ '%s: Process %s found running at pid #%s.' "amcleanup" "${search_name}" "${search_pid}"`
 							kill_pid=${search_pid}
 							kill_name=${search_name}
 							PIDS_FOUND=`expr ${PIDS} + 1`
@@ -207,20 +221,20 @@ if test ${KILL_ENABLE} -eq 1 ; then
 					done
 					if test ! -z "${kill_pid}" ; then
 						if test -d /proc/${kill_pid} ; then
-							echo "amcleanup: Sending process ${kill_pid} the TERM signal."
+							echo `_ '%s: Sending process %s the %s signal.' "$0" "${kill_pid}" "TERM"`
 							kill -15 -- ${kill_pid}
 							sleep 5
 							if test -d /proc/${kill_pid} ; then
-								echo "amcleanup: Sending process  ${kill_pid} the KILL signal."
+								echo `_ '%s: Sending process %s the %s signal.' "$0" "${kill_pid}" "KILL"`
 								kill -9 -- ${kill_pid}
 							fi
 							sleep 5
 							if test -d /proc/${kill_pid} ; then
-								echo "amcleanup: Process ${kill_pid} did not respond to the KILL signal (and may be hung)!" 1>&2
+								echo `_ '%s: Process %s did not respond to the %s signal (and may be hung)!' "$0" "${kill_pid}" "KILL"` 1>&2
 								KILL_FAILURES=`expr ${KILL_FAILURES} + 1`
 							fi
 						else
-							echo "amcleanup: Process ${kill_pid} no longer running.  Skipping..."
+							echo `_ '%s: Process %s no longer running.  Skipping...' "$0" "${kill_pid}"`
 						fi
 					fi
 				done
@@ -232,10 +246,10 @@ if test ${KILL_ENABLE} -eq 1 ; then
 			fi
 		done
 		if test ${PIDS_FOUND} -gt 0 ; then
-			echo "amcleanup: ${PIDS_FOUND} Amanda processes were found running."
-			echo "amcleanup: ${KILL_FAILURES} processes failed to terminate."
+			echo `_ '%s: %s Amanda processes were found running.' "$0" "${PIDS_FOUND}"`
+			echo `_ '%s: %s processes failed to terminate.' "$0" "${KILL_FAILURES}"`
 		else
-			echo "amcleanup: No Amanda processes were found running."
+			echo `_ '%s: No Amanda processes were found running.' "$0"`
 		fi
 		cd "${PREVIOUS_DIR}"
 	fi
@@ -243,12 +257,12 @@ fi
 
 retstatus=0
 if test -f $logfile ; then
-	echo "amcleanup: processing outstanding log file."
+	echo `_ '%s: processing outstanding log file.' "$0"`
 	exec </dev/null >/dev/null 2>&1
 	amreport$SUF $conf "$@"
 	rc=$?
 	if test $rc -ne 0 ; then
-		echo "amcleanup: amreport exited with status: $rc" 1>&2
+		echo `_ '%s: "%s" exited with status: %s' "$0" "amreport" "$rc"` 1>&2
 		retstatus=`expr $retstatus + 1`
 	fi
 
@@ -256,7 +270,7 @@ if test -f $logfile ; then
 	amlogroll$SUF $conf "$@"
 	rc=$?
 	if test $rc -ne 0 ; then
-		echo "acmleanup: amlogroll exited with status: $rc" 1>&2
+		echo `_ '%s: "%s" exited with status: %s' "$0" "amlogroll" "$rc"` 1>&2
 		retstatus=`expr $retstatus + 2`
 	fi
 
@@ -264,18 +278,18 @@ if test -f $logfile ; then
 	amtrmidx$SUF $conf "$@"
 	rc=$?
 	if test $rc -ne 0 ; then
-		echo "amcleanup: amtrmidx exited with status: $rc" 1>&2
+		echo `_ '%s: "%s" exited with status: %s' "$0" "amtrmidx" "$rc"` 1>&2
 		retstatus=`expr $retstatus + 4`
 	fi
 
 else
-	echo "amcleanup: no unprocessed logfile to clean up."
+	echo `_ '%s: no unprocessed logfile to clean up.' "$0"`
 fi
 
 if test -f $errfile ; then
     # if log was found, this will have been directed to /dev/null,
     # which is fine.
-    echo "amcleanup: $errfile exists, renaming it."
+    echo `_ '%s: %s exists, renaming it.' "$0" "$errfile"`
 
     # Keep debug log through the tapecycle plus a couple days
     maxdays=`expr $tapecycle + 2`
@@ -298,7 +312,7 @@ fi
 if test -f $erramflush ; then
     # if log was found, this will have been directed to /dev/null,
     # which is fine.
-    echo "amcleanup: $erramflush exists, renaming it."
+    echo `_ '%s: %s exists, renaming it.' "$0" "$erramflush"`
 
     # Keep debug log through the tapecycle plus a couple days
     maxdays=`expr $tapecycle + 2`
@@ -321,7 +335,7 @@ fi
 $libexecdir/amcleanupdisk $conf "$@"
 rc=$?
 if test $rc -ne 0 ; then
-	echo "amcleanup: amcleanupdisk exited with status: $rc" 1>&2
+	echo `_ '%s: "%s" exited with status: %s' "$0" "amcleanupdisk" "$rc"` 1>&2
 	retstatus=`expr $retstatus + 8`
 fi
 
diff --git a/server-src/amdump.sh.in b/server-src/amdump.sh.in
--- a/server-src/amdump.sh.in
+++ b/server-src/amdump.sh.in
@@ -47,9 +47,24 @@ else
 	SUF=
 fi
 
+#+
+# Function to:
+#    Simplify gettext usage by allowing printf format
+#    strings for translators, use _() identifier for
+#    xgettext extraction similar to "C" usage and
+#    collapsing "printf `gettext fmt` ...", which is
+#    used everywhere, into one function.
+#-
+_() {
+	fmt=`gettext -d amanda "$1"`
+	shift
+	printf "$fmt" $*
+}
+
+
 if [ $# -lt 1 ]
 then
-        echo "Usage: amdump config [host [disk...]...]" 1>&2
+        echo `_ 'Usage: %s config [host [disk...]...]' "$0"`  1>&2
         exit 1
 fi
 
@@ -57,7 +72,7 @@ exit_status=0;
 
 conf=$1
 if [ ! -d $confdir/$conf ]; then
-    echo "amdump$SUF: could not find directory $confdir/$conf" 1>&2
+    echo `_ '%s: could not find directory %s' "amdump$SUF" "$confdir/$conf"` 1>&2
     exit 1
 fi
 shift
@@ -83,19 +98,19 @@ if [ $? -ne 0 ]; then
 fi
 
 #if [ $runuser != $dumpuser ]; then
-#	echo "amdump: must be run as user $dumpuser, not $runuser" 1>&2
+#	echo `_ '%s: must be run as user %s, not %s' "$0" "$dumpuser" "$runuser"` 1>&2
 #	exit 1
 #fi
 
 if test -f hold; then
-	echo "amdump: waiting for hold file to be removed" 1>&2
+	echo `_ '%s: waiting for hold file to be removed' "$0"` 1>&2
 	while test -f hold; do
 		sleep 60
 	done
 fi
 
 if test -f $errfile || test -f $logdir/log; then
-	echo "amdump: amdump or amflush is already running, or you must run amcleanup" 1>&2
+	echo `_ '%s: amdump or amflush is already running, or you must run amcleanup' "$0"` 1>&2
 	exit 1
 fi
 
@@ -110,13 +125,13 @@ exit_code=$?
 exec </dev/null 2>>$errfile 1>&2
 exit_code=$?
 [ $exit_code -ne 0 ] && exit_status=$exit_code
-echo "amdump: start at `date`"
-echo "amdump: datestamp `date +%Y%m%d`"
-echo "amdump: starttime `date +%Y%m%d%H%M%S`"
+printf '%s: start at %s\n' "amdump" "`date`"
+printf '%s: datestamp %s\n' "amdump" "`date +%Y%m%d`"
+printf '%s: starttime %s\n' "amdump" "`date +%Y%m%d%H%M%S`"
 $libexecdir/planner$SUF $conf "$@" | $libexecdir/driver$SUF $conf "$@"
 exit_code=$?
 [ $exit_code -ne 0 ] && exit_status=$exit_code
-echo "amdump: end at `date`"
+printf '%s: end at %s\n' "amdump" "`date`"
 
 # Send out a report on the dumps.
 $sbindir/amreport$SUF $conf "$@"
diff --git a/server-src/amfreetapes.sh.in b/server-src/amfreetapes.sh.in
--- a/server-src/amfreetapes.sh.in
+++ b/server-src/amfreetapes.sh.in
@@ -15,6 +15,21 @@ export PATH
 
 Program=`basename $0`
 
+#+
+# Function to:
+#    Simplify gettext usage by allowing printf format
+#    strings for translators, use _() identifier for
+#    xgettext extraction similar to "C" usage and
+#    collapsing "printf `gettext fmt` ...", which is
+#    used everywhere, into one function.
+#-
+function _() {
+	fmt=`gettext -d amanda "$1"`
+	shift
+	printf "$fmt" $*
+}
+
+
 log () {
 	echo 1>&2 "$@"
 	return 0
@@ -61,9 +76,9 @@ fi
 AllTapeList="${TapeList}.all"
 
 [ ! -f $AllTapeList ] \
-	&& echo "no tapelist $AllTapeList found" >&2 \
+	&& echo `_ 'no tapelist %s found' "$AllTapeList"` >&2 \
 	&& cat $TapeList | sed 's/^.* //' | sort -u > $AllTapeList \
-	&& echo "$AllTapeList created" >&2
+	&& echo `_ '%s created' "$AllTapeList"` >&2
 
 cat $TapeList | sed 's/^.* //' > $AllTapeList.n
 cat $AllTapeList >> $AllTapeList.n
@@ -71,24 +86,24 @@ sort -u $AllTapeList.n > $AllTapeList && rm -f $AllTapeList.n
 
 MAXTAPE=`cat $AllTapeList | sed "s/^$VOLHEADER//" | sort -n | tail -1`
 NEXTTAPE=`expr $MAXTAPE + 1`
-echo "last Tape is ${VOLHEADER}${MAXTAPE}" >&2
+echo `_ 'last Tape is %s' "${VOLHEADER}${MAXTAPE}"` >&2
 
 I=1
 while [ $I -le $MAXTAPE ]; do
 	WRITTEN=`grep "${VOLHEADER}${I}\$" $TapeList`
 	EXISTS=`grep "${VOLHEADER}${I}\$" $AllTapeList`
 	if [ "$EXISTS" = "" -a "$WRITTEN" = "" ]; then
-		echo "missing tape ${VOLHEADER}${I}" >&2
+		echo `_ 'missing tape %s' "${VOLHEADER}${I}"` >&2
 		echo "${VOLHEADER}${I}" >> $AllTapeList \
-		&& echo "added ${VOLHEADER}${I} to $AllTapeList" >&2
+		&& echo `_ 'added %s to %s' "${VOLHEADER}${I}" "$AllTapeList"` >&2
 	elif [ "$EXISTS" = "" -a "$WRITTEN" != "" ]; then
-		echo "tape written, but not existing: ${VOLHEADER}${I}" >&2
+		echo `_ 'tape written, but not existing: %s' "${VOLHEADER}${I}"` >&2
 	elif [ "$EXISTS" != "" -a "$WRITTEN" = "" ]; then
-		echo "free tape: ${VOLHEADER}${I}" >&2
+		echo `_ 'free tape: %s' "${VOLHEADER}${I}"` >&2
 	fi
 	I=`expr $I + 1`
 done
 
-echo "next tape is ${VOLHEADER}${NEXTTAPE}" >&2
+echo `_ 'next tape is %s' "${VOLHEADER}${NEXTTAPE}"` >&2
 
 exit 0
diff --git a/server-src/amverify.sh.in b/server-src/amverify.sh.in
--- a/server-src/amverify.sh.in
+++ b/server-src/amverify.sh.in
@@ -23,6 +23,21 @@ else
 	SUF=
 fi
 
+#+
+# Function to:
+#    Simplify gettext usage by allowing printf format
+#    strings for translators, use _() identifier for
+#    xgettext extraction similar to "C" usage and
+#    collapsing "printf `gettext fmt` ...", which is
+#    used everywhere, into one function.
+#-
+function _() {
+	fmt=`gettext -d amanda "$1"`
+	shift
+	printf "$fmt" $*
+}
+
+
 # If the shell/system echo support \r and \c, use them to write some
 # status messages over the top of each other as things progress, otherwise
 # use a normal echo and let them go on new lines.  Define $Echoe to be
@@ -70,12 +85,12 @@ getparm() {
 sendreport() {
 	if [ -f $REPORT -a X"$REPORTTO" != X"" ]; then
 		(
-		echo "Tapes: $TAPELIST"
+		echo `_ 'Tapes: %s' "$TAPELIST"`
 		if [ -s $DEFECTS ]; then
-			echo "Errors found: "
+			echo `_ 'Errors found:'`
 			cat $DEFECTS
 		else
-			echo "No errors found!"
+			echo `_ 'No errors found!'`
 		fi
 		echo
 
@@ -116,7 +131,7 @@ doonefile() {
 	CMD=
 	result=1
 	if [ X"$HEADER" = X"" ]; then
-		echo "** No header" > $TEMP/errors
+		echo `_ '** No header'` > $TEMP/errors
 	else
 		set X $HEADER
 		# XXX meh, while[] is dangerous, what about a bad header?
@@ -151,11 +166,11 @@ doonefile() {
 				CMD=$XFSRESTORE
 				ARGS="-t -v silent -"
 			else
-				echo "** Cannot do $2 dumps" > $TEMP/errors
+				echo `_ '** Cannot do %s dumps' "$2"` > $TEMP/errors
 				result=999	# flag as not really an error
 			fi
 		else
-			echo "** Cannot find dump type" > $TEMP/errors
+			echo `_ '** Cannot find dump type'` > $TEMP/errors
 		fi
 	fi
 	echo $CMD > $TEMP/onefile.cmd
@@ -169,7 +184,7 @@ doonefile() {
 			$CMD $ARGS > /dev/null 2> $TEMP/errors
 			result=$?
 		else
-			echo "** Cannot execute $CMD" > $TEMP/errors
+			echo `_ '** Cannot execute %s' "$CMD"` > $TEMP/errors
 		fi
 	fi
 	cat >/dev/null				# soak up the rest of the image
@@ -343,7 +358,7 @@ REPORT=$TEMP/report; rm -f $REPORT
 TAPELIST=
 EXITSTAT=$TEMP/amrecover.exit; rm -rf $EXITSTAT
 
-trap 'report "aborted!"; echo "aborted!" >> $DEFECTS; sendreport; rm -fr $TEMP; exit 1' 1 2 3 4 5 6 7 8 10 12 13 14 15
+trap 'report "aborted!"; echo `_ 'aborted!'` >> $DEFECTS; sendreport; rm -fr $TEMP; exit 1' 1 2 3 4 5 6 7 8 10 12 13 14 15
 
 $Echoe "Defects file is $DEFECTS"
 report "amverify $CONFIG"
@@ -429,7 +444,7 @@ while [ $SLOT -lt $SLOTS ]; do
 	ERRORS=0
 	while [ $ERG = 0 ]; do
 		if [ $Echon = echon ]; then
-			$Echon "Waiting for device to go ready..."
+			$Echon `_ 'Waiting for device to go ready...'`
 		fi
 		count=1800
 		until eval $DEVICE_READY > $TEMP/ammt.out 2>&1; do
@@ -442,7 +457,7 @@ while [ $SLOT -lt $SLOTS ]; do
 			count=`expr $count - 3`
 		done
 		if [ $Echon = echon ]; then
-			$Echon "Reading..."
+			$Echon `_ 'Reading...'`
 		fi
 		RESULT=`$AMRESTORE -h -p $DEVICE 2> $TEMP/amrestore.out \
 			| doonefile 2> $TEMP/onefile.errors`
