Merged revisions 10999 via zmerge from svn+ssh://martineau@natasha/home/cvs/svn/amanda/trunk
........
  r10999 | martineau | 2008-04-21 18:43:39 -0400 (Mon, 21 Apr 2008) | 34 lines
  
  BugId: 4406
  * changer-src/chg-lib.sh.in (amdevcheck_status):
    Set amdevcheck_message.
  * changer-src/chg-chs.sh, changer-src/chg-juke.sh,
    changer-src/chg-manual.sh, changer-src/chg-zd-mtx.sh,
    changer-src/chg-multi.sh: Output amdevcheck_message
  * device-src/device.c: Set errmsg and status.
    device_open always return a device, the status and errmsg are set.
  * device-src/device.h: Define DeviceStatusFlags.
  * device-src/null-device.c, device-src/s3-device.c,
    device-src/tape-device.c, device-src/vfs-device.c,
    device-src/rait-device.c: Set errmsg and status.
  * device-src/tape-posix.c: Return status for VOLUME_MISSING.
  * device-src/tape-ops.h: Remove TapeCheckResult.
  * server-src/taper-source.h (_TaperSource): Add errmsg.
  * server-src/taper-source.c: Set errmsg
  * server-src/amcheck.c, server-src/amtape.c, server-src/amlabel.c,
    server-src/taperscan.c, restore-src/amrestore.c,
    restore-src/restore.c: Use status and errmsg of a device.
  * server-src/taper-disk-port-source.c: Set errmsg.
  * server-src/reporter.c: Fix parsing of taper PARTIAL line.
  * server-src/taper.c: Use errmsg for device and _TaperSource.
  * server-src/taper-file-source.c: Set errmsg.
  * server-src/amcheckdump.pl,
    server-src/amdevcheck.pl: Use status and errmsg from device.
  * perl/Amanda/Changer.pm: Fix for DEVICE_STATUS_*.
  * perl/Amanda/Device.swg: New interface.
  * installcheck/Makefile.am: Don't print some commands.
  * installcheck/Amanda_Device.pl: Check new device api.
  * common-src/queueing.c: Use new queue_fd_t.
  * common-src/queueing.h (queue_fd_t): new struct.
  * common-src/amanda-sh-lib.sh.in: Fix bug.
  * common-src/queueing-test.c: Use queue_fd_t.
........


git-svn-id: https://amanda.svn.sourceforge.net/svnroot/amanda/amanda/trunk@979 a8d146d6-cc15-0410-8900-af154a0219e0

diff --git a/changer-src/chg-lib.sh.in b/changer-src/chg-lib.sh.in
--- a/changer-src/chg-lib.sh.in
+++ b/changer-src/chg-lib.sh.in
@@ -89,21 +89,29 @@ tape_device_filename() {
              print $2 if ($1 || "tape") eq "tape"' "$1"
 }
 
-# Runs amdevcheck to find out if a particular device is usable. Finds the
-# config name based on pwd, so run it from the config directory. The sole
-# argument should be the device name to check. Note that amdevcheck can FP
-# on device status, since some devices can't differentiate between device
-# problems and an unlabeled volume.
+# Invoke amdevcheck to determine whether the device is ready for use.
+#
+# @return 0 if a tape is loaded or error
+# @return 1 if a tape is tape offline or busy
+#
+# @side-effect: $amdevcheck_message is the contents of all MESSAGE lines from
+#               amdevcheck, suitable for use in higher-level error messages
 amdevcheck_status() {
-    amdevcheck_config_dir=`pwd`
-    amdevcheck_config_name=`basename $amdevcheck_config_dir`
-    amdevcheck_output=`amdevcheck $amdevcheck_config_name $@`
+    amdevcheck_message=
+    local amdevcheck_config_dir=`pwd`
+    local amdevcheck_config_name=`basename $amdevcheck_config_dir`
+    local amdevcheck_output=`amdevcheck $amdevcheck_config_name $@`
 
-    if test $? -eq 0 || \
-        echo $amdevcheck_output | grep UNLABELED > /dev/null; then
-        return 0
-    else
+    test $? -ne 0 && return 0
+
+    # extract any messages
+    amdevcheck_message=`echo "$amdevcheck_output" | sed '/^MESSAGE /{s/^MESSAGE //;p}; d'`
+
+    # Return 1 if a tape offline or busy
+    if echo "$amdevcheck_output" | $EGREP "VOLUME_MISSING|DEVICE_BUSY" > /dev/null; then
         return 1
+    else
+        return 0
     fi
 }
 
