* device-src/tape-posix.c: return DEVICE_ERROR|DEVICE_BUSY on EIO * changer-src/chg-lib.sh.in: keep waiting for a device if it *might*   be busy or offline
git-svn-id: https://amanda.svn.sourceforge.net/svnroot/amanda/amanda/trunk@1145 a8d146d6-cc15-0410-8900-af154a0219e0

diff --git a/changer-src/chg-lib.sh.in b/changer-src/chg-lib.sh.in
--- a/changer-src/chg-lib.sh.in
+++ b/changer-src/chg-lib.sh.in
@@ -101,17 +101,23 @@ amdevcheck_status() {
     local amdevcheck_config_dir=`pwd`
     local amdevcheck_config_name=`basename $amdevcheck_config_dir`
     local amdevcheck_output=`amdevcheck $amdevcheck_config_name $@`
+    local amdevcheck_status=$?
 
-    test $? -ne 0 && return 0
+    Log `_ 'Output from amdevcheck: (status %s)' "$amdevcheck_status"`
+    Log $amdevcheck_output
+
+    test "$amdevcheck_status" -ne 0 && return 0
 
     # extract any messages
     amdevcheck_message=`echo "$amdevcheck_output" | sed '/^MESSAGE /{s/^MESSAGE //;p}; d'`
 
-    # Return 1 if a tape offline or busy
-    if echo "$amdevcheck_output" | $EGREP -v "MESSAGE|VOLUME_MISSING|DEVICE_BUSY" > /dev/null; then
-        return 0
+    # Return 1 if it's possible that the device is offline or busy; if the device cannot
+    # distinguish this state from an error condition, then our caller will just have to
+    # time out
+    if echo "$amdevcheck_output" | $EGREP "VOLUME_MISSING|DEVICE_BUSY" > /dev/null; then
+	return 1
     else
-        return 1
+	return 0
     fi
 }
 
