not much real change

diff --git a/autogen b/autogen
--- a/autogen
+++ b/autogen
@@ -1,10 +1,7 @@
-#! /bin/sh
+#!/usr/bin/env bash
 
 # cd to the directory we're run from
 cd `dirname $0`
-
-# if you change this, please also change it in the root Makefile.am
-includes="-I . -I config -I config/gettext-macros -I config/gnulib -I config/amanda -I config/macro-archive -I /usr/share/aclocal"
 
 [ -d /opt/csw/gnu ] && export PATH=/opt/csw/gnu:${PATH}
 
@@ -26,8 +23,14 @@ echo " * gettext macros"
 echo " * gnulib"
 echo " * libtool files"
 
+amanda_cfg="./config"
+amanda_version_setup=set_full_version
+# if you change this, please also change it in the root Makefile.am
+includes="-I. -Iconfig -I$amanda_cfg -I$amanda_cfg/gettext-macros -I$amanda_cfg/gnulib -I$amanda_cfg/amanda -I$amanda_cfg/macro-archive -I/usr/share/aclocal"
+
+# file-list are included files in top Makefile.am
 echo "..creating file lists"
-(   cd config
+(   cd $amanda_cfg
     for m4dir in amanda gettext-macros gnulib macro-archive; do
 	echo "## this file is automatically generated by autogen" > "$m4dir/file-list"
 	for f in $m4dir/*.m4; do echo "EXTRA_DIST += $f" >> "$m4dir/file-list"; done
@@ -37,14 +40,25 @@ echo "..creating file lists"
     for f in automake/*.am; do echo "EXTRA_DIST += $f" >> "automake/file-list"; done
 )
 
-#set the FULL_VERSION file
-config/set_full_version
+echo "..generate FULL_VERSION"
+# use the real path... if a symlink
+p=$(readlink -e config/$amanda_version_setup); 
+$p || die "$amanda_version_setup failed"
+
+# get autoconf / automake from all one place ... or dont succeed
+autoconf_path=$(command -v libtoolize)
+autoconf_path=${autoconf_path%/*}
+
+# for Solaris, only for autoconf tools, ... prefer /usr/bin as a binary path
+[ -x /usr/bin/libtoolize ] && autoconf_path=/usr/bin
+
+export PATH=${autoconf_path}:${PATH}
 
 # replace local tools with the custom versions
-command -v libtoolize >/dev/null && libtoolize -i --force
+( p=$(command -v libtoolize); set -x; $p -i; )
 
 # need 2.63 or later autoconf/autom4te
-AUTOM4TE="$(ls -1 /usr/bin/autom4te2[6789]* /usr/bin/autom4te[3-9]* 2>/dev/null)"
+AUTOM4TE="$(ls -1 $autoconf_path/autom4te2[6789]* $autoconf_path/autom4te[3-9]* 2>/dev/null)"
 # last space-separated word only..
 AUTOM4TE=${AUTOM4TE##* }
 AUTOM4TE=${AUTOM4TE##*\n}
@@ -54,8 +68,8 @@ AC_VERSION_SFX="${AUTOM4TE##*autom4te}"
 export AUTOM4TE="autom4te${AC_VERSION_SFX}"
 export AUTOCONF="autoconf${AC_VERSION_SFX}"
 
-echo "..aclocal with version $AC_VERSION_SFX"
-aclocal --install $includes || die "aclocal failed"
+echo "..aclocal${AC_VERSION_SFX:-  [default aclocal version]} setup"
+( p=$(command -v aclocal); set -x; $p --install $includes; ) || die "aclocal failed"
 
 echo "...aclocal patches"
 # See http://bugzilla.gnome.org/show_bug.cgi?id=418778
@@ -69,10 +83,12 @@ sed -e  \
      aclocal.m4 > aclocal.m4~ && mv aclocal.m4~ aclocal.m4
 
 echo "..autoconf with version $AC_VERSION_SFX"
-autoconf${AC_VERSION_SFX} || die "autoconf failed"
+( p=$(command -v autoconf${AC_VERSION_SFX}); set -x; $p; ) || die "autoconf${AC_VERSION_SFX:-  [default autoconf version]} failed"
 echo "..autoheader with version $AC_VERSION_SFX"
-autoheader${AC_VERSION_SFX} || die "autoheader failed"
+( p=$(command -v autoheader${AC_VERSION_SFX}); set -x; $p; ) || die "autoheader${AC_VERSION_SFX:-  [default autoheader version]} failed"
 touch config/config.h.in
 
 echo "..automake"
-automake --add-missing --force --copy --warnings=none || die "automake failed"
+( p=$(command -v automake); set -x; $p --add-missing --force --copy --warnings=none; ) || die "automake failed"
+
+echo "autogen has completed"
