* autogen configure.in config/macro-archive/*.m4   config/amanda/*.m4 config/libtool/*.m4: move most autoconf   checks to macros in .m4 files.  Hilights of changes along the way:   - use AC_REQUIRES to enforce check ordering   - Add a post-configure summary of important results   - use AM_CONDITIONAL to control conditional compilation of whole     files, instead of preprocessor macros   - correct spelling of PRINCIPLE -> PRINCIPAL   - remove support for dbmalloc (we use valgrind, coverity, etc. now)   - remove support for infofiles in anything but text format   - change DONT_SUID_ROOT to !WANT_SETUID_ROOT   - remove unused --with-broken-fsf   - remove multiple unused function and header checks, the defines     from which do not appear in any source file   - remove LTLIBOBJS cruft based on     http://www.delorie.com/gnu/docs/autoconf/autoconf_165.html   - remove unused LTALLOCA definition based on     http://www.delorie.com/gnu/docs/libtool/libtool_30.html   - use autoconf macro archive's     AC_DEFINE_DIR to expand $prefix, etc. in directory variables   - do not *require* --with-{user,group}; this allows 'make distcheck'     to run successfully * docs/developing.txt: describe how to update gnulib, libtool, and   gettext * po/reautopoint.patch po/reautopoint: script to update gettext,   parallel to gnulib/regenerate/regenerate * amandad-src/amandad.c changer-src/scsi-aix.c   changer-src/scsi-bsd.c changer-src/scsi-cam.c   changer-src/scsi-changer-driver.c changer-src/scsi-chio.c   changer-src/scsi-hpux.c changer-src/scsi-hpux_new.c   changer-src/scsi-irix.c changer-src/scsi-linux.c   changer-src/scsi-proto.c changer-src/scsi-solaris.c   changer-src/sense.c client-src/calcsize.c client-src/getfsent.c   client-src/selfcheck.c client-src/sendbackup.c   client-src/sendsize.c common-src/alloc.c common-src/amanda.h   common-src/conffile.c common-src/debug.c common-src/file.c   common-src/genversion.c common-src/krb4-security.c   common-src/writev.c device-src/tape-posix.c server-src/amadmin.c   server-src/amcheck.c server-src/amlabel.c server-src/amlogroll.c   server-src/amtape.c server-src/amtrmidx.c server-src/amtrmlog.c   server-src/changer.c server-src/chunker.c server-src/diskfile.c   server-src/driver.c server-src/dumper.c server-src/getconf.c   server-src/infofile.c server-src/infofile.h server-src/planner.c   server-src/reporter.c tape-src/output-tape.c: changes corresponding   to simplifications and fixes in autoconf * gnulib/regenerate/no-error.patch gnulib/regenerate/regenerate: no   need to create gnulib.m4i anymore
git-svn-id: https://amanda.svn.sourceforge.net/svnroot/amanda/amanda/trunk@566 a8d146d6-cc15-0410-8900-af154a0219e0

diff --git a/autogen b/autogen
--- a/autogen
+++ b/autogen
@@ -3,31 +3,47 @@
 # autoconf 2.13 and automake 1.4 or newer are required
 # arguments are forwarded to the autoreconf script.
 
+# cd to the directory we're run from
 cd `dirname $0`
 
+# if you change this, please also change it in the root Makefile.am
+includes="-I . -I config -I config/gettext-macros -I config/gnulib -I config/amanda -I config/macro-archive"
+
+# clean up
+rm -f aclocal.m4
+rm -rf autom4te*.cache
+rm -f configure
+
+die() {
+    echo x"${@}" | sed s/^x//
+    exit 1
+}
+
+echo "See docs/developing.txt for instructions on updating:"
+echo " * gettext macros"
+echo " * gnulib"
+echo " * libtool files"
+
+echo "..creating file lists"
+(   cd config
+    for m4dir in amanda gettext-macros gnulib macro-archive; do
+	echo "## this file is automatically generated by autogen" > "$m4dir/file-list"
+	for f in $m4dir/*.m4; do echo "EXTRA_DIST += $f" >> "$m4dir/file-list"; done
+    done
+
+    echo "## this file is automatically generated by autogen" > "automake/file-list"
+    for f in automake/*.am; do echo "EXTRA_DIST += $f" >> "automake/file-list"; done
+)
+
+echo "..aclocal"
+aclocal $includes || die "aclocal failed"
+
+echo "..autoconf"
+autoconf || die "autoconf failed"
+
+echo "..autoheader"
+autoheader || die "autoheader failed"
 touch config/config.h.in
 
-#if test x`ls -1t acinclude.m4 2>/dev/null \
-#	    config/gettext.m4i config/gnulib.m4i config/acinclude.m4i config/libtool.m4i |
-#	  sed 1q` != x"acinclude.m4"; then
-    rm -f acinclude.m4
-    # keep libtool.m4i first here, as it has a "serial number" comment that it wants
-    # first in the file
-    cat config/libtool.m4i config/gettext.m4i config/gnulib.m4i config/acinclude.m4i \
-	config/docbook-dtd.m4i config/xsltproc.m4i \
-	config/docbook-xslt-min.m4i config/docbook-xslt.m4i config/ax_compare_version.m4i \
-	> acinclude.m4 
-#fi
-
-# Regenerate aclocal.m4
-aclocal --force
-rc=$?
-if test $rc -ne 0; then
-	echo aclocal failed 1>&2
-else
-	# Now reconfigure...
-	automake --add-missing
-	autoreconf --warning=syntax --warning=no-portability --force ${1+"$@"}
-	rc=$?
-fi
-exit $rc
+echo "..automake"
+automake --add-missing --force --copy --warnings=none || die "automake failed"
