* client-src/selfcheck.c: fix formatting typo * common-src/security.h: fix prototypes in comments * common-src/security-util.c common-src/util.c: fix vstralloc errors * common-src/debug.c common-src/amanda.h: remove debug_prefix_time * changer-src/scsi-linux.c changer-src/chg-scsi-chio.c   changer-src/scsi-cam.c client-src/calcsize.c recover-src/amrecover.c   server-src/driver.c client-src/sendbackup-gnutar.c server-src/find.c   server-src/diskfile.c : format string / i18n tweaks * common-src/amcrypt-ossl.sh.in: fix shell quoting
git-svn-id: https://amanda.svn.sourceforge.net/svnroot/amanda/amanda/trunk@403 a8d146d6-cc15-0410-8900-af154a0219e0

diff --git a/common-src/amcrypt-ossl.sh.in b/common-src/amcrypt-ossl.sh.in
--- a/common-src/amcrypt-ossl.sh.in
+++ b/common-src/amcrypt-ossl.sh.in
@@ -36,7 +36,7 @@ if [ -z "${OPENSSL:=`which openssl`}" ]; then
 	echo `_ '%s: openssl not found' "${ME}"` >&2
 	exit 1
 elif [ ! -x "${OPENSSL}" ]; then
-	echo `_ '%s: can't execute %s (%s)' "${ME}" "openssl" "${OPENSSL}"` >&2
+	echo `_ "%s: can't execute %s (%s)" "${ME}" "openssl" "${OPENSSL}"` >&2
 	exit 1
 fi
 
