misc small tweaks
git-svn-id: https://amanda.svn.sourceforge.net/svnroot/amanda/amanda/trunk@395 a8d146d6-cc15-0410-8900-af154a0219e0

diff --git a/common-src/amcrypt-ossl-asym.sh.in b/common-src/amcrypt-ossl-asym.sh.in
--- a/common-src/amcrypt-ossl-asym.sh.in
+++ b/common-src/amcrypt-ossl-asym.sh.in
@@ -44,7 +44,7 @@ PRIVKEY=$AMANDA_HOME/backup-privkey.pem
 PUBKEY=$AMANDA_HOME/backup-pubkey.pem
 
 # where might openssl be?
-PATH=/bin:/usr/bin:/usr/local/bin:/usr/ssl/bin:/usr/local/ssl/bin
+PATH=/bin:/usr/bin:/usr/local/bin:/usr/ssl/bin:/usr/local/ssl/bin:/opt/csw/bin
 export PATH
 MAGIC='AmAnDa+OpEnSsL'
 ME=`basename "$0"`
@@ -70,7 +70,7 @@ if [ -z "${OPENSSL:=`which openssl`}" ]; then
 	echo `_ '%s: %s not found' "${ME}" "openssl"` >&2
 	exit 1
 elif [ ! -x "${OPENSSL}" ]; then
-	echo `_ "%s: can't execute openssl (%s)" "${ME}" "${OPENSSL}"` >&2
+	echo `_ "%s: can't execute %s (%s)" "${ME}" "openssl" "${OPENSSL}"` >&2
 	exit 1
 fi
 
diff --git a/common-src/amcrypt-ossl.sh.in b/common-src/amcrypt-ossl.sh.in
--- a/common-src/amcrypt-ossl.sh.in
+++ b/common-src/amcrypt-ossl.sh.in
@@ -13,7 +13,7 @@ export RANDFILE
 PASSPHRASE=$AMANDA_HOME/.am_passphrase	# required
 
 # where might openssl be?
-PATH=/bin:/usr/bin:/usr/local/bin:/usr/ssl/bin:/usr/local/ssl/bin
+PATH=/bin:/usr/bin:/usr/local/bin:/usr/ssl/bin:/usr/local/ssl/bin:/opt/csw/bin
 export PATH
 ME=`basename "$0"`
 
@@ -33,10 +33,10 @@ _() {
 
 
 if [ -z "${OPENSSL:=`which openssl`}" ]; then
-	echo `_ '%s: %s not found' "${ME}" "openssl"` >&2
+	echo `_ '%s: openssl not found' "${ME}"` >&2
 	exit 1
 elif [ ! -x "${OPENSSL}" ]; then
-	echo `_ '%s: can't execute openssl (%s)' "${ME}" "${OPENSSL}"` >&2
+	echo `_ '%s: can't execute %s (%s)' "${ME}" "openssl" "${OPENSSL}"` >&2
 	exit 1
 fi
 
diff --git a/common-src/amcrypt.sh.in b/common-src/amcrypt.sh.in
--- a/common-src/amcrypt.sh.in
+++ b/common-src/amcrypt.sh.in
@@ -13,7 +13,7 @@ AMANDA_HOME=~@CLIENT_LOGIN@
 
 AM_AESPIPE=@sbindir@/amaespipe
 AM_PASSPHRASE=$AMANDA_HOME/.am_passphrase
-PATH=/usr/bin:/usr/local/bin:/sbin:/usr/sbin
+PATH=/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/opt/csw/bin
 export PATH
 
 AESPIPE=`which aespipe`
@@ -34,7 +34,7 @@ _() {
 
 
 if [ $? -ne 0 ] ; then
-	echo `_ '%s: %s not found in %s' "$0" "aespipe" "$PATH"` >&2
+	echo `_ '%s: %s was not found in %s' "$0" "aespipe" "$PATH"` >&2
         exit 2
 fi
 
