remove mention of Enterprise and modernize slightly

diff --git a/packaging/common/set_zmanda_version b/packaging/common/set_zmanda_version
--- a/packaging/common/set_zmanda_version
+++ b/packaging/common/set_zmanda_version
@@ -1,24 +1,20 @@
 #!/usr/bin/env bash
 #
-# This script is run by extension's autogen and amanda enterprise's builddist
-# to create the FULL_VERSION and PKG_REV files.  Amanda Enterprise ignores the
-# contents of VERSION because it comes from community and is static.  Instead
-# Amanda Enterprise uses git branch or tag names.  Amanda Enterprise
-# Extensions does not have a VERSION file.
+# This script is run by extension's autogen and amanda's builddist
+# to create the FULL_VERSION and PKG_REV files.  This build ignores the
+# contents of VERSION because it is old and often out of date.  Instead
+# Amanda uses git branch or tag names. 
 #
 # If run from a tag, the value of VERSION is the branch or tag name
 # reformatted.
-#
-# Extensions ./configure uses FULL_VERSION in the macro ZAMANDA_VERSION (from
-# config/zmanda_version.m4) to avoid hard coding the a version string.
-# Amanda Enterprise ./configure has an equivalent macro AMANDA_INIT_VERSION
 #set -x
 
 # only if called externally ...
-[ $0 -ef ${BASH_SOURCE[0]} ] && ref=${1:-HEAD}
+[ $0 -ef ${BASH_SOURCE[0]} ] && gitref=${1:-HEAD}
 
+selfdir=$(dirname ${BASH_SOURCE[0]})
 if [ "$(type -t get_yearly_tag)" != "function" ]; then
-    . packaging/common/build_functions.sh
+    . ${selfdir}/build_functions.sh
 fi
 
 [ -x "$(command -v gsed)" ] && eval "sed() { command gsed \"\$@\"; }"
@@ -29,9 +25,9 @@ sed --version | grep -i 'GNU sed' >/dev/null || exit 1;
 
 
 # Fall back to previous build (or dist build?)?
-if ! [ -d .git ]; then
+if ! [ -e .git ]; then
     [ -f FULL_VERSION -a -f PKG_REV ] && exit 0
-    echo "Error: No subversion or git info available!"   #### ERROR
+    echo "Error: $(pwd): No subversion or git info available!"   #### ERROR
     exit 1
 fi
 
