fixes and refactors to build scripts

diff --git a/config/set_full_version b/config/set_full_version
--- a/config/set_full_version
+++ b/config/set_full_version
@@ -1,83 +1,91 @@
 #!/bin/bash
 #
-# This script is run by autogen to create the FULL_VERSION file.
+# This script is run by extension's autogen and amanda enterprise's builddist
+# to create the FULL_VERSION and PKG_REV files.  Amanda Enterprise ignores the
+# contents of VERSION because it comes from community and is static.  Instead
+# Amanda Enterprise uses svn/git branch or tag names.  Amanda Enterprise
+# Extensions does not have a VERSION file.
 #
-# If run from a git branch, it append '.git.' + git sha1 to the VERSION file.
-# If run from a svn branch, it append '.svn.' + svn number to the VERSION file.
-# If run from a svn tag that match /rc/ it use only the tag name to set the
-#  VERSION, this is done specifically for zmanda rc build.
-# If run from a svn tag that doesn't match /rc/ it use only the VERSION file.
+# If run from a tag, the value of VERSION is the branch or tag name
+# reformatted.
 #
-# It is important to update the VERSION file before creating a tag.
-#
-# ./autogen run config/set_full_version, it create the FULL_VERSION file.
-# ./configure use the FULL_VERSION file.
-#
-srcdir=$1
+# Extensions ./configure uses FULL_VERSION in the macro ZAMANDA_VERSION (from
+# config/zmanda_version.m4) to avoid hard coding the a version string.
+# Amanda Enterprise ./configure has an equivalent macro AMANDA_INIT_VERSION
+#set -x
 
+if [ "$(type -t save_version)" != "function" ]; then
+. packaging/common_z/build_functions.sh
+fi
+
+# Set variables so that builddist might run on different platforms
+os=`uname`
+
+SED=$(type -p gsed || type -p sed)
+MAKE=$(type -p gmake || type -p make)
+GREP=$(type -p ggrep || type -p grep)
+
+[ $SED != $(type -p sed) ] && eval "sed() { $SED \"\$@\"; }"
+[ $MAKE != $(type -p make) ] && eval "make() { $MAKE \"\$@\"; }"
+[ $GREP != $(type -p grep) ] && eval "grep() { $GREP \"\$@\"; }"
+
+sed --version | grep -i 'GNU sed' >/dev/null || exit 1;
+
+# regex strings for grep and sed
+flavors="deb..\|mac..\|nexenta..\|rpm..\|sun.."
+qa_rc="qa..\|rc.."
+
+# Version control system repository information is sometimes hard to get. Save
+# it for later consumption.
 if test -d .svn; then
-    svn info . > conftemp.svn
+    svn info . > vcs_repo.info
+    VCS=svn
+elif test -d .git; then
+    git remote -v show > vcs_repo.info
+    git --no-pager log --max-count=1 >> vcs_repo.info
+    VCS=git
+    echo "VCS=git"
+# Fall back to previous build (or dist build?)
+elif test -f FULL_VERSION && test -f PKG_REV; then
+    # nothing to do.
+    exit 0
 else
-    echo "" > conftemp.svn
+    echo "Error: No subversion or git info available!"
+    exit 1
 fi
 
-if test -d .svn && ( grep Revision: conftemp.svn > /dev/null; ); then
-#if grep Revision: conftemp.svn > /dev/null ; then
-    SVN_REV=`grep Revision: conftemp.svn|cut -d: -f 2|cut -c2-`
-    SVN_URL=`grep URL: conftemp.svn|cut -d: -f 2-|cut -c2-`
-    SVN_PATH=`grep URL: conftemp.svn|cut -d "/" -f 8-`
-    SVN_TYPE=`echo ${SVN_PATH} |cut -d "/" -f 1`
-    SVN_BRANCH=`echo "${SVN_PATH}"| cut -d "/" -f 2`
-    url=`grep URL: conftemp.svn|cut -d: -f 2-|cut -c2-`
+## Read repository data, set REV, BRANCH, and TYPE.
+# SVN
+if test $VCS = "svn" && ( grep Revision: vcs_repo.info > /dev/null; ); then
+    get_svn_info
+# git
+elif test $VCS = "git"; then
+    get_git_info $(git rev-parse HEAD)
+    echo "git_rev : $REV"
+    echo "git_branch : $BRANCH"
+    echo "git_long_branch : $LONG_BRANCH"
 fi
 
-if test -d .git; then
-    GIT_SHA1=`git rev-parse HEAD | cut -c -8 `
-fi
+## Generate version from repository data.
+if test -n "${BRANCH}${REV}"; then
+    set_pkg_rev
+    set_version
 
-if test -f FULL_VERSION; then
-    FULL_VERSION_FILE="FULL_VERSION"
-    OLD_VERSION=`cat $FULL_VERSION_FILE`
-else if test -n "$srcdir" -a -f $srcdir/FULL_VERSION; then
-    FULL_VERSION_FILE="$srcdir/FULL_VERSION"
-    OLD_VERSION=`cat $FULL_VERSION_FILE`
+    # Amanda makes it easy to "force" a version string: just set FULL_VERSION
+    # *after* running autogen
+    echo "..version substitution"
+    echo "SET_VERSION : $VERSION"
+    printf "$VERSION" > FULL_VERSION
+
+    BUILD_VERSION="$(git submodule foreach --quiet "git rev-parse --short HEAD"  | sed -e 'N' -e '$y/\n/./' )"
+    printf "$BUILD_VERSION" > BUILD_VERSION
+
+    # Write out LONG_VERSION for installer build script.
+    echo "SET_LONG_BRANCH : $LONG_BRANCH"
+    printf "$LONG_BRANCH" > LONG_BRANCH
 else
-    FULL_VERSION_FILE="FULL_VERSION"
-    OLD_VERSION=
-fi
-fi
-
-if test -n "$srcdir"; then
-    VERSION_FILE="$srcdir/VERSION"
-else
-    VERSION_FILE="VERSION"
-fi
-VERSION=`cat $VERSION_FILE`
-
-if test -n "$SVN_REV"; then
-    if test "${SVN_TYPE}" = "branches"; then
-        VERSION=${VERSION}.svn.${SVN_REV}
-    else if test "${SVN_TYPE}" = "trunk"; then
-        VERSION=${VERSION}.svn.${SVN_REV}
-    else
-        RC=`echo "${SVN_BRANCH}"| grep "rc"`
-        if test -n "$RC"; then
-	    VERSION=`echo "${SVN_BRANCH}"| sed 's/[^0-9]*// ; s/[_.]//g'`
-	    VERSION=`echo ${VERSION}| sed 's/^\([0-9]\)\([0-9]\)\([0-9]\)/\1.\2.\3/'`
-        fi
-    fi
-    fi
-
-else if test -n "$GIT_SHA1"; then
-    VERSION=${VERSION}".git."${GIT_SHA1}
-
-else if test -n "$OLD_VERSION"; then
-    VERSION=$OLD_VERSION
-fi
-fi
-fi
-
-if test "$VERSION" != "$OLD_VERSION" -o $VERSION_FILE -nt FULL_VERSION; then
-    echo "$VERSION" > FULL_VERSION
+    # uhoh, we couldn't set the version!
+    echo "Couldn't set FULL_VERSION or PKG_REV!"
+    exit 1
 fi
 
diff --git a/installcheck/Makefile.am b/installcheck/Makefile.am
--- a/installcheck/Makefile.am
+++ b/installcheck/Makefile.am
@@ -2,6 +2,8 @@ include $(top_srcdir)/config/automake/vars.am
 include $(top_srcdir)/config/automake/scripts.am
 all_tests =
 
+bin_dirs = $(strip $(wildcard $(top_srcdir)/bitrock-stack/*/bin))
+
 common_tests = \
 	Amanda_Archive \
 	Amanda_Config \
@@ -274,6 +276,10 @@ EXTRA_DIST += $(catalogs)
 noinst_SCRIPTS = \
 	run-ndmp
 
+PERL = $(top_srcdir)/bitrock-stack/perl/bin/perl
+
+BUILT_SOURCES = installcheck-build
+
 CHECK_PERL_FLAGS=-I$(top_srcdir)/installcheck
 
 SCRIPTS_PERL = $(tests) $(mocks) $(noinst_SCRIPTS) amcat-error amcat-error-end amcat-error-no-exec
@@ -284,27 +290,35 @@ SCRIPTS_EXTRA_DIST = $(all_tests)
 # skip syntax checks on these files, since we're about to run all of them
 SKIP_CHECKS = yes
 
+installcheck-build: $(SCRIPTS_PERL) $(SCRIPTS_SHELL)
+	[ -x amcat-error-no-exec ] && chmod a-x amcat-error-no-exec || true
+	[ -O . ] && chmod a+w . || true
+	for f in $(tests); do [ -x $$f ] && chmod a-x $$f; true; done
+	[ -d $(top_srcdir)/bitrock-stack/common/include ] && \
+		( cd $(top_srcdir)/bitrock-stack; git checkout -f .; git clean -dfx; ./build-var-subst.sh; ) || true
+
 .PHONY: clobber_my_config_is_ok
-clobber_my_config_is_ok:
+clobber_my_config_is_ok: installcheck-build
 	@if test "$(CONFIG_CLOBBER_MY_CONFIG)" != "OK" -a \
                  "$(CLOBBER_MY_CONFIG)" != "OK"; then \
 		echo ""; \
 		echo "'make installcheck' is a dangerous tool.  It will overwrite your"; \
 		echo "amanda-client.conf and amandates, and (if it triggers an as-yet undetected"; \
 		echo "bug) may do other unexpected things.  You are strongly encouraged"; \
-		echo "  - not to run installchecks on a production install"; \
-		echo "  - not to run installchecks as root"; \
+		echo "  - not to run installcheck on a production install"; \
+		echo "  - not to run installcheck as root"; \
 		echo "See http://wiki.zmanda.com/index.php/Testing for instructions on setting up a"; \
 		echo "test environment in which potential damage is limited by your filesystem's"; \
-		echo "permissions.  To actually run the installchecks, invoke make as follows:"; \
+		echo "permissions.  To actually run the installcheck, invoke make as follows:"; \
 		echo "  $(MAKE) CLOBBER_MY_CONFIG=OK installcheck"; \
 		exit 1; \
 	fi
+	export PATH="$$(echo "$(bin_dirs)" | tr ' ' ':'):$${PATH}"; \
+		( type starman || { echo "starman not found in path"; exit -1; } )
 
 # newer Test::Harness (v3.18-3.21) implementations get confused by executable
 # test scripts, so this rule chmod a-x's them first
-installcheck-local: clobber_my_config_is_ok $(SCRIPTS_PERL) $(SCRIPTS_SHELL)
-	chmod a-x amcat-error-no-exec
+installcheck-prep: clobber_my_config_is_ok
 	rm -rf "$(AMANDA_TMPDIR)/installchecks"
 	$(MKDIR_P) "$(AMANDA_TMPDIR)/installchecks"
 	@if test -f "$(CONFIG_DIR)/amanda-client.conf" -a ! -f "$(CONFIG_DIR)/amanda-client.conf.install-backup"; then \
@@ -316,8 +330,13 @@ installcheck-local: clobber_my_config_is_ok $(SCRIPTS_PERL) $(SCRIPTS_SHELL)
 	@if test -f "$(CONFIG_DIR)/template.d/tapetypes" -a ! -f "$(CONFIG_DIR)/template.d/tapetypes.install-backup"; then \
 	    cp "$(CONFIG_DIR)/template.d/tapetypes" "$(CONFIG_DIR)/template.d/tapetypes.install-backup"; \
 	fi
-	for f in $(tests); do chmod a-x $$f; done
-	srcdir="$(srcdir)" $(PERL) -I$(srcdir) -I. -e 'use Test::Harness qw(&runtests); runtests(sort @ARGV);' $(tests)
+
+installcheck-run: installcheck-prep
+	srcdir="$(srcdir)" \
+	PATH="$$(echo "$(bin_dirs)" | tr ' ' ':'):$${PATH}" \
+		$(PERL) -I$(srcdir) -I. -e 'use Test::Harness qw(&runtests); runtests(sort @ARGV);' $(tests)
+
+installcheck-local: installcheck-run
 	rm -rf "$(CONFIG_DIR)/TESTCONF"
 	@if test -f "$(CONFIG_DIR)/amanda-client.conf.install-backup"; then \
 	    mv -f "$(CONFIG_DIR)/amanda-client.conf.install-backup" "$(CONFIG_DIR)/amanda-client.conf"; \
