* merged changes from branches/3_3 * packaging/common/common_functions.sh: remove trailing whitespace,   remove redundant usage of ${BASEDIR} in solaris functions, avoid   potentially non-portable test invocations. * packaging/common/test_sh_libs.sh: fix some log messages, redirect   some unused output, split check_user_* tests into shorter testsr,   add tests for supplemental groups, fix running single test. * packaging/common/mock_utils.sh: change id to error if any flags are   given, add mock for groups. * packaging/common/post_inst_functions.sh: remove redundant leading / * packaging/common/post_rm_functions.sh: rm trailing whitespace. * packaging/common/pre_inst_functions.sh: use variable for user   shell, clarify log messages regarding user accounts, split   check_user into separate functions, mostly to ease testing, add   check_user_supplemental_group. * packaging/deb/rules: use FULL_VERSION file to fill AMVER var, use * concatenation trick for postinst, rm trailing whitespace * packaging/deb/buildpkg: process postinst.src postrm.src preinst.src with substitute.pl * packaging/deb/postinst.src: refactor to use common functions. * packaging/deb/amanda-backup-server.postrm,   packaging/deb/amanda-backup-client.postrm,   packaging/deb/amanda-backup-client.postinst,   packaging/deb/amanda-backup-server.postinst: delete everything, add   variables pkg_type and other_pkg_type. * packaging/deb/preinst: moved to... * packaging/deb/preinst.src: here. refactor using common functions * packaging/deb/postrm: moved to... * packaging/deb/postrm.src: here. refactor using common functions. * packaging/rpm/amanda.spec.src: refactor to use common functions * packaging/rpm/buildpkg: check for ./configure, and exit if   substitute.pl fails. * packaging/sun-pkg/buildpkg: * packaging/sun-pkg/client/postremove.src,   packaging/sun-pkg/server/postremove.src: remove redundant usage of   basedir. * packaging/sun-pkg/client/postinstall.src,   packaging/sun-pkg/server/postinstall.src: same as above, plus fix   case statement. * packaging/sun-pkg/server/preinstall.src,   packaging/sun-pkg/client/preinstall.src: remove redundant basedir,   use new check_user_* functions.
git-svn-id: https://amanda.svn.sourceforge.net/svnroot/amanda/amanda/trunk@4826 a8d146d6-cc15-0410-8900-af154a0219e0

diff --git a/packaging/deb/amanda-backup-client.postinst b/packaging/deb/amanda-backup-client.postinst
--- a/packaging/deb/amanda-backup-client.postinst
+++ b/packaging/deb/amanda-backup-client.postinst
@@ -1,104 +1,5 @@
 #!/bin/sh
-
-SYSCONFDIR="/etc"
-LOCALSTATEDIR="/var"
-LOGDIR="${LOCALSTATEDIR}/log/amanda/"
-AMANDAHOMEDIR="${LOCALSTATEDIR}/lib/amanda"
-amanda_user=amandabackup
-amanda_group=disk
-xinetd_reload="restart"
-
-
-# Installing xinetd config and make it active.
-if [ -e /etc/xinetd.d ] && [ -d /etc/xinetd.d ] ; then
-	if [ ! -f /etc/xinetd.d/amandaclient ] ; then
-		cp ${AMANDAHOMEDIR}/example/xinetd.amandaclient /etc/xinetd.d/amandaclient || exit 1
-		echo -n "`date +'%b %e %Y %T'`: Reloading xinetd configuration..." 
-		if [ "${xinetd_reload}" = "reload" ] ; then
-			/usr/sbin/invoke-rc.d xinetd ${xinetd_reload} # don't exit yet...
-			if [ $? -ne 0 ] ; then
-				echo -n "reload failed.  Attempting restart..." 
-				/usr/sbin/invoke-rc.d xinetd restart || exit 1
-			fi
-		else
-			/usr/sbin/invoke-rc.d xinetd ${xinetd_reload} || exit 1
-		fi
-	fi
-fi
-
-echo "`date +'%b %e %Y %T'`: Installing '${LOCALSTATEDIR}/amanda/amandates'." 
-if [ ! -f ${LOCALSTATEDIR}/amanda/amandates ] ; then
-	touch ${LOCALSTATEDIR}/amanda/amandates || exit 1
-fi
-echo "`date +'%b %e %Y %T'`: Ensuring correct permissions for '${LOCALSTATEDIR}/amanda/amandates'." 
-chown ${amanda_user}:${amanda_group} ${LOCALSTATEDIR}/amanda/amandates || exit 1
-chmod 0640 ${LOCALSTATEDIR}/amanda/amandates || exit 1
-if [ -x /sbin/restorecon ] ; then
-      /sbin/restorecon ${LOCALSTATEDIR}/amanda/amandates  || exit 1
-fi
-
-# Install .amandahosts to client
-echo "`date +'%b %e %Y %T'`: Checking '${AMANDAHOMEDIR}/.amandahosts' file." 
-if [ ! -f ${AMANDAHOMEDIR}/.amandahosts ] ; then
-	touch ${AMANDAHOMEDIR}/.amandahosts || exit 1
-fi
-for host in localhost localhost.localdomain ; do
-		if [ -z "`grep \"^${host}[[:blank:]]\+${amanda_user}[[:blank:]]\+amdump\" ${AMANDAHOMEDIR}/.amandahosts`" ] ; then
-			echo "${host} ${amanda_user} amdump" >> "${AMANDAHOMEDIR}/.amandahosts" || exit 1
-		fi
-done
-chown ${amanda_user}:${amanda_group} ${AMANDAHOMEDIR}/.amandahosts || exit 1
-chmod 0600 ${AMANDAHOMEDIR}/.amandahosts || exit 1
-
-# Install amanda client configuration file
-echo "`date +'%b %e %Y %T'`: Checking '${SYSCONFDIR}/amanda/amanda-client.conf' file." 
-if [ ! -f ${SYSCONFDIR}/amanda/amanda-client.conf ] ; then
-	cp ${AMANDAHOMEDIR}/example/amanda-client.conf ${SYSCONFDIR}/amanda/amanda-client.conf || exit 1
-fi
-chown ${amanda_user}:${amanda_group} ${SYSCONFDIR}/amanda/amanda-client.conf || exit 1
-chmod 0600 ${SYSCONFDIR}/amanda/amanda-client.conf || exit 1
-
-# Install .gnupg directory
-echo "`date +'%b %e %Y %T'`: Installing '${AMANDAHOMEDIR}/.gnupg'." 
-if [ ! -d ${AMANDAHOMEDIR}/.gnupg ] ; then
-	echo "`date +'%b %e %Y %T'`: '${AMANDAHOMEDIR}/.gnupg' will be created." 
-	mkdir ${AMANDAHOMEDIR}/.gnupg || exit 1
-fi
-echo "`date +'%b %e %Y %T'`: Ensuring correct permissions for '${AMANDAHOMEDIR}/.gnupg'." 
-chown ${amanda_user}:${amanda_group} ${AMANDAHOMEDIR}/.gnupg || exit 1
-chmod 700 ${AMANDAHOMEDIR}/.gnupg || exit 1
-
-# SSH RSA key generation on client for amrecover
-KEYDIR="${AMANDAHOMEDIR}/.ssh"
-KEYFILE="id_rsa_amrecover"
-COMMENT="root@client"
-if [ ! -d ${KEYDIR} ] ; then
-	if [ -f ${KEYDIR} ] ; then
-		echo "`date +'%b %e %Y %T'`: Directory '${KEYDIR}' exists as a file.  Renaming to '${KEYDIR}.save'." 
-		mv ${KEYDIR} ${KEYDIR}.save || exit 1
-	fi
-	echo "`date +'%b %e %Y %T'`: Creating directory '${KEYDIR}'." 
-	mkdir ${KEYDIR} || exit 1
-fi
-if [ ! -f ${KEYDIR}/${KEYFILE} ] ; then
-	echo "`date +'%b %e %Y %T'`: Creating ssh RSA key in '${KEYDIR}/${KEYFILE}'" 
-	ssh-keygen -q -C $COMMENT -t rsa -f ${KEYDIR}/${KEYFILE} -N '' || exit 1
-fi
-echo "`date +'%b %e %Y %T'`: Setting permissions for '${KEYDIR}' and '${KEYDIR}/${KEYFILE}*'" 
-chown ${amanda_user}:${amanda_group} ${KEYDIR} || exit 1
-chmod 0750 ${KEYDIR} || exit 1
-chmod 0600 ${KEYDIR}/${KEYFILE}* || exit 1
-
-# environment variables (~amandabackup/.profile)
-echo "`date +'%b %e %Y %T'`: Checking for '${AMANDAHOMEDIR}/.profile' and ensuring correct environment." 
-if [ ! -f ${AMANDAHOMEDIR}/.profile ] ; then
-	touch ${AMANDAHOMEDIR}/.profile || exit 1
-fi
-if [ -z "`grep PATH ${AMANDAHOMEDIR}/.profile | grep '/usr/sbin'`" ] ; then
-	echo "export PATH=\"\$PATH:/usr/sbin/\"" >> "${AMANDAHOMEDIR}/.profile" || exit 1
-fi
-echo "`date +'%b %e %Y %T'`: Setting ownership and permissions for '${AMANDAHOMEDIR}/.profile'" 
-chown ${amanda_user}:${amanda_group} ${AMANDAHOMEDIR}/.profile || exit 1
-chmod 0640 ${AMANDAHOMEDIR}/.profile || exit 1
-
-echo "`date +'%b %e %Y %T'`: === Amanda backup client installation complete. ===" 
+# Debian recommends this.  Script exits on simple command failure.
+# set -e
+pkg_type=client
+other_pkg_type=server
