adding current state of 3_6 branch

diff --git a/packaging/deb/buildpkg b/packaging/deb/buildpkg
--- a/packaging/deb/buildpkg
+++ b/packaging/deb/buildpkg
@@ -1,56 +1,40 @@
 #!/bin/bash
 
-#
-# VERSION: the identifier for the amanda determined from git
-#	information.
-# PKG_NAME_VER: the full version name of amanda we're working on.  This will
-#	become part of the deb name.  {PKG_NAME_VER} gets substituted
-#
-
 buildtype=${1:-both}
 shift
 
-BUILDVER="4.0"
-GIT_DIR=.git/modules/tools-archives \
-   git ls-files stack-output/php | grep -q . &&
-   unset BUILDVER
-
 # set the var buildpkg_dir as well
 . ./packaging/common/build_functions.sh
+. ./packaging/common/set_zmanda_version
+detect_package_vars
 
 # . ./packaging/common/set_zmanda_version
 
 export PKG_DIR=$(realpath .)
-mach=`uname -m`
 
 do_deb_package() {
-    gen_pkg_build_config $@
+    gen_pkg_build_config "$@"
     gen_pkg_environ
     do_package "${PKG_NAME_VER}"
 }
 
 set -e
 
-case "$buildtype,$mach,$BUILDVER" in
-   both,x86_64,*)
-        do_deb_package "$buildpkg_dir/server${BUILDVER}"
-        do_deb_package "$buildpkg_dir/client${BUILDVER}"
+case "$buildtype" in
+   both)
+        do_deb_package "$buildpkg_dir/server"
+        do_deb_package "$buildpkg_dir/client"
         ;;
 
-   server,x86_64,*)
-        do_deb_package "$buildpkg_dir/server${BUILDVER}"
+   server)
+        do_deb_package "$buildpkg_dir/server"
         ;;
 
-   client,*,*) ;&
-   both,*,*)
-        do_deb_package "$buildpkg_dir/client${BUILDVER}"
+   client)
+        do_deb_package "$buildpkg_dir/client"
         ;;
 
-#   platform,x86_64,*)
-#       do_deb_package "$buildpkg_dir/zmanda-platform${BUILDVER}.spec"
-#       ;;
-
-   *) echo "ERROR: cannot build combination of $buildtype-$mach-${BUILDVER:-3.6}" >&2; exit -1 ;;
+   *) echo "ERROR: cannot build combination of $buildtype" >&2; exit -1 ;;
 esac
 
 true
diff --git a/packaging/sun-pkg/buildpkg b/packaging/sun-pkg/buildpkg
--- a/packaging/sun-pkg/buildpkg
+++ b/packaging/sun-pkg/buildpkg
@@ -10,10 +10,10 @@
 buildtype=${1:-both}
 shift
 
-BUILDVER="4.0"
 # set the var buildpkg_dir as well
 . ./packaging/common/build_functions.sh
 . ./packaging/common/set_zmanda_version
+detect_package_vars
 
 [ -d /opt/csw/gnu ] && [[ "$PATH" != */opt/csw/gnu* ]] && PATH=/opt/csw/gnu:${PATH}
 [ -d /usr/sfw/bin ] && [[ "$PATH" != */usr/sfw/bin* ]] && PATH=/usr/sfw/bin:${PATH}
@@ -21,7 +21,6 @@ BUILDVER="4.0"
 
 export PATH
 export PKG_DIR=$(realpath .)
-mach=`uname -m`
 
 do_sun_package() {
     gen_pkg_build_config "$@"
@@ -31,27 +30,21 @@ do_sun_package() {
 
 set -e
 
-case "$buildtype,$mach,$BUILDVER" in
-#   both,x86_64,*)
-#        do_sun_package "$buildpkg_dir/server${BUILDVER}"
-#        do_sun_package "$buildpkg_dir/client${BUILDVER}"
-#        ;;
-
-#   server,x86_64,*)
-   server,*,*)
-        do_sun_package "$buildpkg_dir/server${BUILDVER}"
+case "$buildtype" in
+   both)
+        do_sun_package "$buildpkg_dir/server"
+        do_sun_package "$buildpkg_dir/client"
         ;;
 
-   client,*,*) ;&
-   both,*,*)
-        do_sun_package "$buildpkg_dir/client${BUILDVER}"
+   server)
+        do_sun_package "$buildpkg_dir/server"
         ;;
 
-#   platform,x86_64,*)
-#       do_sun_package "$buildpkg_dir/zmanda-platform${BUILDVER}.spec"
-#       ;;
+   client)
+        do_sun_package "$buildpkg_dir/client"
+        ;;
 
-   *) echo "ERROR: cannot build combination of $buildtype-$mach-${BUILDVER:-3.6}" >&2; exit -1 ;;
+   *) echo "ERROR: cannot build combination of $buildtype" >&2; exit -1 ;;
 esac
 
 true
