add without fixing or reducing it yet

diff --git a/packaging/deb/buildpkg b/packaging/deb/buildpkg
--- a/packaging/deb/buildpkg
+++ b/packaging/deb/buildpkg
@@ -1,34 +1,57 @@
-#! /bin/bash
-# We're assuming that you've copied packaging/* from the 
-# amanda-extensions source tree to the amanda source tree.  
+#!/bin/bash
 
-# Buildpkg is designed to be used by both buildbot (to automate deb production)
-# and by J Random User (to build a deb for kicks).
 #
-# VERSION: the identifier for the amanda determined from subversion
-#	information.  
+# VERSION: the identifier for the amanda determined from git
+#	information.
 # PKG_NAME_VER: the full version name of amanda we're working on.  This will
-#	become part of the deb name.  {PKG_NAME_VER} gets substituted into
-#	various package files.  
+#	become part of the deb name.  {PKG_NAME_VER} gets substituted
 #
-# Other Hints:
-# Not everyone will want to use the ./configure options we provide.  The
-# easiest way to change them is by editing the rules file.  This fairly easy:
-# rules is a Makefile, so follow gnu makefile rules and edit the define 
-# CONFIG_FLAGS_COMMON variable.  Don't forget trailing backslashes.
-# set -x
 
-# set pkg_root also
-pkg_name=amanda
-. ./packaging/common/build_functions.sh
+buildtype=${1:-both}
+shift
 
-# create version files from top ...
-. ./config/set_full_version
+BUILDVER="4.0"
+GIT_DIR=.git/modules/tools-archives \
+   git ls-files stack-output/php | grep -q . &&
+   BUILDVER=""
 
-gen_pkg_build_config $pkg_root
+[ $buildtype = platform ] && pkg_name=zmanda-platforms
 
-gen_pkg_environ
+# set the var buildpkg_dir as well
+. ./packaging/common_z/build_functions.sh
+. ./packaging/common_z/set_zmanda_version
 
-[ -n "$PKG_NAME_VER" ] || { declare -p; die "no version to use"; }
+export PKG_DIR=$(realpath .)
+mach=`uname -m`
 
-do_package ${PKG_NAME_VER}
+do_deb_package() {
+    gen_pkg_build_config "$@"
+    gen_pkg_environ
+    do_package "${PKG_NAME_VER}"
+}
+
+set -e
+
+case "$buildtype,$mach,$BUILDVER" in
+   both,x86_64,*)
+        do_deb_package "$buildpkg_dir/server${BUILDVER}"
+        do_deb_package "$buildpkg_dir/client${BUILDVER}"
+        ;;
+
+   server,x86_64,*)
+        do_deb_package "$buildpkg_dir/server${BUILDVER}"
+        ;;
+
+   client,*,*) ;&
+   both,*,*)
+        do_deb_package "$buildpkg_dir/client${BUILDVER}"
+        ;;
+
+#   platform,x86_64,*)
+#       do_deb_package "$buildpkg_dir/zmanda-platform${BUILDVER}.spec"
+#       ;;
+
+   *) echo "ERROR: cannot build combination of $buildtype-$mach-${BUILDVER:-3.6}" >&2; exit -1 ;;
+esac
+
+true
diff --git a/packaging/rpm/build b/packaging/rpm/build
--- a/packaging/rpm/build
+++ b/packaging/rpm/build
@@ -1,34 +1,26 @@
 #!/bin/bash
-# We're assuming that you've copied packaging/* from the 
-# amanda-extensions source tree to the amanda source tree.
-# (buildbot dist tarballs will not contain packaging files!)
 
-# Buildpkg script for producing RPM packages. (Does not require root access.)
-# Buildpkg is designed to be used by both buildbot (to automate rpm production)
-# and by J Random User (to build an rpm for kicks).
-#
-# VERSION: the identifier for the amanda determined from subversion
-#	information.  
-# PKG_NAME_VER: the full version name of amanda we're working on.  This will
-#	become part of the rpm name.  
-# PKG_TARBALL: the name of the tarball which contains the source code.  it must
-#     unpack into a directory named PKG_NAME_VER. 
-# PKG_DIR: Rpmbuild expects absolute paths, so we provide this var.  It also
-#     allows you to build somewhere other than `pwd`.  You probably don't want
-#     to use the system-wide location, as the script tries to blow these
-#     directories away.
-# 
-# Other Hints:
-# Not everyone will want to use the ./configure options we provide.  The
-# easiest way to change them is by editing the .spec file.  This isn't so
-# easy, unfortunately.  Look at the %build section, and the %define xxxx 
-# statements immediately above it. good luck.
+DEFINES=
+[[ "$*" == *release* ]] && DEFINES=(--define 'bundle release' --define 'bitrock_build 1')
+ODEFINES="${DEFINES[@]}"
 
-pkg_name=amanda
-. packaging/common/build_functions.sh
+buildtype=${1:-both}
+shift
 
-set_zmanda_version HEAD
+# must set before including build-functions.sh
+[ $buildtype = platform ] && pkg_name=zmanda-platforms
 
+BUILDVER="4.0"
+git --git-dir=.git/modules/tools-archives \
+   ls-files stack-output/php | grep -q . &&
+   unset BUILDVER
+
+# set the var buildpkg_dir as well
+. ./packaging/common_z/build_functions.sh
+. ./packaging/common_z/set_zmanda_version
+
+export PKG_DIR=$(realpath .)
+mach=`uname -m`
 
 do_rpm_package() {
     gen_pkg_build_config $buildpkg_dir
@@ -43,4 +35,38 @@ do_rpm_package() {
 
 set -e
 
-do_rpm_package "amanda.spec"
+case "$buildtype,$mach,$BUILDVER" in
+   both,x86_64,*)
+#        do_rpm_package "amanda_enterprise${BUILDVER}.spec" \
+#              "${DEFINES[@]}" \
+#              --define "subpkg server"
+        #
+#        STACK_BRANCH=none do_rpm_package "amanda_enterprise_client${BUILDVER}.spec" \
+#              --define "subpkg client"
+        #
+        exit 100
+        ;;
+
+   server,x86_64,*)
+        do_rpm_package "amanda_enterprise${BUILDVER}.spec" \
+              "${DEFINES[@]}" \
+              --define "subpkg server"
+
+
+        ;;
+
+   client,*,*) ;&  both,*,*)
+	STACK_BRANCH=none do_rpm_package "amanda_enterprise_client${BUILDVER}.spec" \
+              --define "subpkg client"
+
+      ;;
+
+   platform,x86_64,*)
+	do_rpm_package "zmanda-platform${BUILDVER}.spec" \
+              "${DEFINES[@]}"
+      ;;
+
+   *) echo "ERROR: cannot build combination of $buildtype-$mach-${BUILDVER:-3.6}" >&2; exit -1 ;;
+esac
+
+true
diff --git a/packaging/rpm/buildpkg b/packaging/rpm/buildpkg
--- a/packaging/rpm/buildpkg
+++ b/packaging/rpm/buildpkg
@@ -1,30 +1,26 @@
 #!/bin/bash
 
-# Buildpkg script for producing RPM packages. (Does not require root access.)
-# Buildpkg is designed to be used by both buildbot (to automate rpm production)
-# and by J Random User (to build an rpm for kicks).  The odd way of handling
-# all optioins through environment variables is a product of buildbot.
-#
-# AMVER: the version of amanda we're working on.  This will become part of the
-#     rpm name.  AMVER must line up with the version number mentioned in the
-#     .spec file.
-# PKG_DIR: Rpmbuild expects absolute paths, so we provide this var.  It also
-#     allows you to build somewhere other than `pwd`.  You probably don't want
-#     to use the system-wide location, as the script tries to blow these
-#     directories away.
-# 
-# Other Hints:
-# Not everyone will want to use the ./configure options we provide.  The
-# easiest way to change them is by editing the .spec file.  This isn't so
-# easy, unfortunately.  Look at the %build section, and the %define xxxx 
-# statements immediately above it. good luck.
+DEFINES=
+[[ " $* " == *\ release\ * ]] && DEFINES=(--define 'bundle release' --define 'bitrock_build 1')
+ODEFINES="${DEFINES[@]}"
 
-pkg_name=amanda
-. packaging/common/build_functions.sh
-. config/set_full_version
+buildtype=${1:-both}
+shift
 
-# Until we get package revisioning in community.
-[ -f "PKG_REV" ] || echo "1" > PKG_REV
+# must set before including build-functions.sh
+[ $buildtype = platform ] && pkg_name=zmanda-platforms
+
+BUILDVER="4.0"
+git --git-dir=.git/modules/tools-archives \
+   ls-files stack-output/php | grep -q . &&
+   unset BUILDVER
+
+# set the var buildpkg_dir as well
+. ./packaging/common_z/build_functions.sh
+# leave set_zmanda_version for later...
+
+export PKG_DIR=$(realpath .)
+mach=`uname -m`
 
 do_rpm_package() {
     gen_pkg_build_config $buildpkg_dir
@@ -37,6 +33,76 @@ do_rpm_package() {
     do_package "$@"
 }
 
+generate_override_version() {
+       local ref=HEAD
+       (
+        unset CDPATH
+        unset PKG_DIR \
+              src_root \
+              pkg_suffix \
+              pkgconf_dir \
+              buildpkg_dir \
+              pkg_bldroot \
+              pkg_name_pkgtime \
+              pkgdirs_top;
+
+        cd ./000-external/tools-archives;
+
+        git rev-parse --verify --quiet __orig_platform >/dev/null && 
+             ref=__orig_platform
+        ../../packaging/common_z/version_setup.sh $ref
+       )
+}
+
+reset_set_zmanda_version() {
+        unset set_zmanda_version
+        set_zmanda_version() {
+            eval "$(get_version_evalstr "$1")"
+            eval "$OVERRIDE_VERSION"
+            declare -g PKG_NAME_VER="$pkg_name-${VERSION}"
+            echo -n "$VERSION" > $src_root/FULL_VERSION
+            echo -n "$BUILD_VERSION" > $src_root/BUILD_VERSION
+            echo -n "$LONG_BRANCH" > $src_root/LONG_BRANCH
+            echo -n "$REV" > $src_root/REV
+            echo -n "$PKG_REV" > $src_root/PKG_REV
+        }
+}
+
 set -e
 
-do_rpm_package "amanda.spec"
+case "$buildtype,$mach,$BUILDVER" in
+   both,x86_64,*)
+        do_rpm_package "amanda_enterprise${BUILDVER}.spec" \
+              "${DEFINES[@]}" \
+              --define "subpkg server"
+        #
+        STACK_BRANCH=none do_rpm_package "amanda_enterprise_client${BUILDVER}.spec" \
+              --define "subpkg client"
+        #
+        ;;
+
+   server,x86_64,*)
+        do_rpm_package "amanda_enterprise${BUILDVER}.spec" \
+              "${DEFINES[@]}" \
+              --define "subpkg server"
+
+        ;;
+
+   client,*,*) ;&  both,*,*)
+	STACK_BRANCH=none do_rpm_package "amanda_enterprise_client${BUILDVER}.spec" \
+              --define "subpkg client"
+
+        ;;
+
+   platform,x86_64,*)
+        generate_override_version | cat -n
+        export OVERRIDE_VERSION="$(generate_override_version)"
+        reset_set_zmanda_version
+	do_rpm_package "zmanda-platform${BUILDVER}.spec" \
+              "${DEFINES[@]}"
+        ;;
+
+   *) echo "ERROR: cannot build combination of $buildtype-$mach-${BUILDVER:-3.6}" >&2; exit -1 ;;
+esac
+
+true
